//PROJECT NAME: Production
//CLASS NAME: IGetJobmatlItem.cs

using System;
using System.Data;
using CSI.Data.CRUD;
using CSI.Data.SQL.UDDT;

namespace CSI.Production
{
	public interface IGetJobMatlItem
	{
		(int? ReturnCode, 
        string item_UM,
		string item_Description,
		int? ItemExists,
		decimal? UMConvFactor,
		int? JobmatlExists,
		int? JobmatlByProduct,
		decimal? item_MatlCost,
		decimal? item_MatlCostConv,
		decimal? item_LaborCost,
		decimal? item_LaborCostConv,
		decimal? item_FovhdCost,
		decimal? item_FovhdCostConv,
		decimal? item_VovhdCost,
		decimal? item_VovhdCostConv,
		decimal? item_OutCost,
		decimal? item_OutCostConv,
		string item_IssueBy,
		int? item_SerialTracked,
		int? item_LotTracked,
		string OutLoc,
		string OutLot,
		decimal? ReqQty,
		decimal? ReqQtyConv,
		decimal? QtyIssued,
		decimal? QtyIssuedConv,
		decimal? PlanCost,
		decimal? PlanCostConv,
		decimal? OnHandQty,
		decimal? OnHandQtyConv,
		decimal? ACost,
		decimal? AMatlCost,
		decimal? ALbrCost,
		decimal? AFovhdCost,
		decimal? AVovhdCost,
		decimal? AOutCost,
		string CostCode,
		string PoitemNonInvAcct,
		string PoitemNonInvAcctUnit1,
		string PoitemNonInvAcctUnit2,
		string PoitemNonInvAcctUnit3,
		string PoitemNonInvAcctUnit4,
		string PoitemNonInvAcctAccessUnit1,
		string PoitemNonInvAcctAccessUnit2,
		string PoitemNonInvAcctAccessUnit3,
		string PoitemNonInvAcctAccessUnit4,
		string Infobar,
		string Prompt,
		string PromptButtons,
		string OutImportDocId,
		int? WCOutside,
		DateTime? JobmatlRecordDate,
		int? TrakcedPieces,
		string ItemDimensionGroup,
		Guid? JobmatlRowPointer,
		int? JobmatlBackFlush,
		string jobmatl_ManufacturerID,
		string manufacturer_ManufacturerName,
		string jobmatl_ManufacturerItem,
		string manufacturerItem_ManufacturerItemDesc) GetJobMatlItemSp(string Item = null,
		string UM = null,
		string Job = null,
		int? Suffix = null,
		int? OperNum = null,
		int? Sequence = null,
		string CurWhse = null,
		int? ExtByScrap = null,
		string PoNum = null,
		int? PoLine = null,
		int? PoRelease = null,
		string item_UM = null,
		string item_Description = null,
		int? ItemExists = null,
		decimal? UMConvFactor = null,
		int? JobmatlExists = null,
		int? JobmatlByProduct = null,
		decimal? item_MatlCost = null,
		decimal? item_MatlCostConv = null,
		decimal? item_LaborCost = null,
		decimal? item_LaborCostConv = null,
		decimal? item_FovhdCost = null,
		decimal? item_FovhdCostConv = null,
		decimal? item_VovhdCost = null,
		decimal? item_VovhdCostConv = null,
		decimal? item_OutCost = null,
		decimal? item_OutCostConv = null,
		string item_IssueBy = null,
		int? item_SerialTracked = null,
		int? item_LotTracked = null,
		string OutLoc = null,
		string OutLot = null,
		decimal? ReqQty = null,
		decimal? ReqQtyConv = null,
		decimal? QtyIssued = null,
		decimal? QtyIssuedConv = null,
		decimal? PlanCost = null,
		decimal? PlanCostConv = null,
		decimal? OnHandQty = null,
		decimal? OnHandQtyConv = null,
		decimal? ACost = null,
		decimal? AMatlCost = null,
		decimal? ALbrCost = null,
		decimal? AFovhdCost = null,
		decimal? AVovhdCost = null,
		decimal? AOutCost = null,
		string CostCode = null,
		string PoitemNonInvAcct = null,
		string PoitemNonInvAcctUnit1 = null,
		string PoitemNonInvAcctUnit2 = null,
		string PoitemNonInvAcctUnit3 = null,
		string PoitemNonInvAcctUnit4 = null,
		string PoitemNonInvAcctAccessUnit1 = null,
		string PoitemNonInvAcctAccessUnit2 = null,
		string PoitemNonInvAcctAccessUnit3 = null,
		string PoitemNonInvAcctAccessUnit4 = null,
		string Infobar = null,
		string Prompt = null,
		string PromptButtons = null,
		string Site = null,
		string OutImportDocId = null,
		int? JmtRETURN = 0,
		int? WCOutside = 0,
		DateTime? JobmatlRecordDate = null,
		int? TrakcedPieces = 0,
		string ItemDimensionGroup = null,
		Guid? JobmatlRowPointer = null,
		int? JobmatlBackFlush = 0,
		string jobmatl_ManufacturerID = null,
		string manufacturer_ManufacturerName = null,
		string jobmatl_ManufacturerItem = null,
		string manufacturerItem_ManufacturerItemDesc = null);
	}
}

