//PROJECT NAME: Material
//CLASS NAME: ICreateEcnEsigCRUD.cs

using System;
using System.Data;
using CSI.Data.CRUD;
using CSI.Data.SQL.UDDT;

namespace CSI.Material
{
	public interface ICreateEcnEsigCRUD
	{
		bool Optional_ModuleForExists();
		ICollectionLoadResponse Optional_Module1Select();
		void Optional_Module1Insert(ICollectionLoadResponse optional_module1LoadResponse);
		bool Tv_ALTGENForExists();
		(string ALTGEN_SpName, int? rowCount) Tv_ALTGEN1Load(string ALTGEN_SpName);
		ICollectionLoadResponse Tv_ALTGEN2Select(string ALTGEN_SpName);
		void Tv_ALTGEN2Delete(ICollectionLoadResponse tv_ALTGEN2LoadResponse);
		(int? Enabled, int? rowCount) Esig_TypeLoad(int? Severity, string EstimateOperation, string Infobar, string CurrentMaterial, string CurrentReference, int? Enabled);
		(string UserDesc, int? rowCount) UsernamesLoad(string UserName, string UserDesc);
		(string ReasonDescription, int? rowCount) ReasonLoad(string ReasonCode, string ReasonDescription);
		ICollectionLoadResponse NontableSelect(string UserName, string UserDesc, string ReasonCode, string ReasonDescription, Guid? EsigRowpointer);
		void NontableInsert(ICollectionLoadResponse nonTableLoadResponse);
		ICollectionLoadResponse EcnSelect(string ECNNum);
		ICollectionLoadResponse Nontable1Select(Guid? EsigRowpointer, int? Counter, string ECNNum);
		void Nontable1Insert(ICollectionLoadResponse nonTable1LoadResponse);
		ICollectionLoadResponse Nontable2Select(Guid? EsigRowpointer, int? Counter, string Stat);
		void Nontable2Insert(ICollectionLoadResponse nonTable2LoadResponse);
		ICollectionLoadResponse Nontable3Select(Guid? EsigRowpointer, int? Counter, string Orig);
		void Nontable3Insert(ICollectionLoadResponse nonTable3LoadResponse);
		ICollectionLoadResponse Nontable4Select(Guid? EsigRowpointer, int? Counter, string ReqDate);
		void Nontable4Insert(ICollectionLoadResponse nonTable4LoadResponse);
		ICollectionLoadResponse Nontable5Select(Guid? EsigRowpointer, int? Counter, string AppDate);
		void Nontable5Insert(ICollectionLoadResponse nonTable5LoadResponse);
		ICollectionLoadResponse Nontable6Select(Guid? EsigRowpointer, int? Counter, string EffectDate);
		void Nontable6Insert(ICollectionLoadResponse nonTable6LoadResponse);
		ICollectionLoadResponse Nontable7Select(Guid? EsigRowpointer, int? Counter, string CompDate);
		void Nontable7Insert(ICollectionLoadResponse nonTable7LoadResponse);
		ICollectionLoadResponse Nontable8Select(Guid? EsigRowpointer, int? Counter, string PriorCode);
		void Nontable8Insert(ICollectionLoadResponse nonTable8LoadResponse);
		ICollectionLoadResponse Nontable9Select(Guid? EsigRowpointer, int? Counter, string PriDescription);
		void Nontable9Insert(ICollectionLoadResponse nonTable9LoadResponse);
		ICollectionLoadResponse Nontable10Select(Guid? EsigRowpointer, int? Counter, string ReasonCode);
		void Nontable10Insert(ICollectionLoadResponse nonTable10LoadResponse);
		ICollectionLoadResponse Nontable11Select(Guid? EsigRowpointer, int? Counter, string ReasonDescription);
		void Nontable11Insert(ICollectionLoadResponse nonTable11LoadResponse);
		ICollectionLoadResponse Nontable12Select(Guid? EsigRowpointer, int? Counter, string DistCode);
		void Nontable12Insert(ICollectionLoadResponse nonTable12LoadResponse);
		ICollectionLoadResponse Nontable13Select(Guid? EsigRowpointer, int? Counter, string DistDescription);
		void Nontable13Insert(ICollectionLoadResponse nonTable13LoadResponse);
		ICollectionLoadResponse Nontable14Select(Guid? EsigRowpointer, int? Counter, string EcnLine);
		void Nontable14Insert(ICollectionLoadResponse nonTable14LoadResponse);
		ICollectionLoadResponse Nontable15Select(Guid? EsigRowpointer, int? Counter, string Job);
		void Nontable15Insert(ICollectionLoadResponse nonTable15LoadResponse);
		ICollectionLoadResponse Nontable16Select(Guid? EsigRowpointer, int? Counter, string Suffix);
		void Nontable16Insert(ICollectionLoadResponse nonTable16LoadResponse);
		ICollectionLoadResponse Nontable17Select(Guid? EsigRowpointer, int? Counter, string ECNItemType);
		void Nontable17Insert(ICollectionLoadResponse nonTable17LoadResponse);
		ICollectionLoadResponse Nontable18Select(Guid? EsigRowpointer, int? Counter, string ActionCode);
		void Nontable18Insert(ICollectionLoadResponse nonTable18LoadResponse);
		ICollectionLoadResponse Nontable19Select(Guid? EsigRowpointer, int? Counter, string EcniGroup);
		void Nontable19Insert(ICollectionLoadResponse nonTable19LoadResponse);
		ICollectionLoadResponse Nontable20Select(Guid? EsigRowpointer, int? Counter, string Item);
		void Nontable20Insert(ICollectionLoadResponse nonTable20LoadResponse);
		ICollectionLoadResponse Nontable21Select(Guid? EsigRowpointer, int? Counter, string ItemDescription);
		void Nontable21Insert(ICollectionLoadResponse nonTable21LoadResponse);
		ICollectionLoadResponse Nontable22Select(Guid? EsigRowpointer, int? Counter, string ItemStat);
		void Nontable22Insert(ICollectionLoadResponse nonTable22LoadResponse);
		ICollectionLoadResponse Nontable23Select(Guid? EsigRowpointer, int? Counter, string Revision);
		void Nontable23Insert(ICollectionLoadResponse nonTable23LoadResponse);
		ICollectionLoadResponse Nontable24Select(Guid? EsigRowpointer, int? Counter, string OperNum);
		void Nontable24Insert(ICollectionLoadResponse nonTable24LoadResponse);
		ICollectionLoadResponse Nontable25Select(Guid? EsigRowpointer, int? Counter, string WC);
		void Nontable25Insert(ICollectionLoadResponse nonTable25LoadResponse);
		ICollectionLoadResponse Nontable26Select(Guid? EsigRowpointer, int? Counter, string WCDescription);
		void Nontable26Insert(ICollectionLoadResponse nonTable26LoadResponse);
		ICollectionLoadResponse Nontable27Select(Guid? EsigRowpointer, int? Counter, string BflushType);
		void Nontable27Insert(ICollectionLoadResponse nonTable27LoadResponse);
		ICollectionLoadResponse Nontable28Select(Guid? EsigRowpointer, int? Counter, string SchedHrs);
		void Nontable28Insert(ICollectionLoadResponse nonTable28LoadResponse);
		ICollectionLoadResponse Nontable29Select(Guid? EsigRowpointer, int? Counter, string RunBasisMch);
		void Nontable29Insert(ICollectionLoadResponse nonTable29LoadResponse);
		ICollectionLoadResponse Nontable30Select(Guid? EsigRowpointer, int? Counter, string RunMchHours);
		void Nontable30Insert(ICollectionLoadResponse nonTable30LoadResponse);
		ICollectionLoadResponse Nontable31Select(Guid? EsigRowpointer, int? Counter, string RunBasisLbr);
		void Nontable31Insert(ICollectionLoadResponse nonTable31LoadResponse);
		ICollectionLoadResponse Nontable32Select(Guid? EsigRowpointer, int? Counter, string RunLbrHours);
		void Nontable32Insert(ICollectionLoadResponse nonTable32LoadResponse);
		ICollectionLoadResponse Nontable33Select(Guid? EsigRowpointer, int? Counter, string MoveHrs);
		void Nontable33Insert(ICollectionLoadResponse nonTable33LoadResponse);
		ICollectionLoadResponse Nontable34Select(Guid? EsigRowpointer, int? Counter, string QueueHrs);
		void Nontable34Insert(ICollectionLoadResponse nonTable34LoadResponse);
		ICollectionLoadResponse Nontable35Select(Guid? EsigRowpointer, int? Counter, string SetupHrs);
		void Nontable35Insert(ICollectionLoadResponse nonTable35LoadResponse);
		ICollectionLoadResponse Nontable36Select(Guid? EsigRowpointer, int? Counter, string FinishHrs);
		void Nontable36Insert(ICollectionLoadResponse nonTable36LoadResponse);
		ICollectionLoadResponse Nontable37Select(Guid? EsigRowpointer, int? Counter, string OffsetHrs);
		void Nontable37Insert(ICollectionLoadResponse nonTable37LoadResponse);
		ICollectionLoadResponse Nontable38Select(Guid? EsigRowpointer, int? Counter, string EffectDate);
		void Nontable38Insert(ICollectionLoadResponse nonTable38LoadResponse);
		ICollectionLoadResponse Nontable39Select(Guid? EsigRowpointer, int? Counter, string ObsDate);
		void Nontable39Insert(ICollectionLoadResponse nonTable39LoadResponse);
		ICollectionLoadResponse Nontable40Select(Guid? EsigRowpointer, int? Counter, string SpecificNoteDesc);
		void Nontable40Insert(ICollectionLoadResponse nonTable40LoadResponse);
		ICollectionLoadResponse Nontable41Select(Guid? EsigRowpointer, int? Counter, string SpecificNoteContent);
		void Nontable41Insert(ICollectionLoadResponse nonTable41LoadResponse);
		ICollectionLoadResponse Nontable42Select(Guid? EsigRowpointer, int? Counter, string EcnLine);
		void Nontable42Insert(ICollectionLoadResponse nonTable42LoadResponse);
		ICollectionLoadResponse Nontable43Select(Guid? EsigRowpointer, int? Counter, string Job);
		void Nontable43Insert(ICollectionLoadResponse nonTable43LoadResponse);
		ICollectionLoadResponse Nontable44Select(Guid? EsigRowpointer, int? Counter, string Suffix);
		void Nontable44Insert(ICollectionLoadResponse nonTable44LoadResponse);
		ICollectionLoadResponse Nontable45Select(Guid? EsigRowpointer, int? Counter, string ECNItemType);
		void Nontable45Insert(ICollectionLoadResponse nonTable45LoadResponse);
		ICollectionLoadResponse Nontable46Select(Guid? EsigRowpointer, int? Counter, string ActionCode);
		void Nontable46Insert(ICollectionLoadResponse nonTable46LoadResponse);
		ICollectionLoadResponse Nontable47Select(Guid? EsigRowpointer, int? Counter, string EcniGroup);
		void Nontable47Insert(ICollectionLoadResponse nonTable47LoadResponse);
		ICollectionLoadResponse Nontable48Select(Guid? EsigRowpointer, int? Counter, string Item);
		void Nontable48Insert(ICollectionLoadResponse nonTable48LoadResponse);
		ICollectionLoadResponse Nontable49Select(Guid? EsigRowpointer, int? Counter, string ItemDescription);
		void Nontable49Insert(ICollectionLoadResponse nonTable49LoadResponse);
		ICollectionLoadResponse Nontable50Select(Guid? EsigRowpointer, int? Counter, string ItemStat);
		void Nontable50Insert(ICollectionLoadResponse nonTable50LoadResponse);
		ICollectionLoadResponse Nontable51Select(Guid? EsigRowpointer, int? Counter, string Revision);
		void Nontable51Insert(ICollectionLoadResponse nonTable51LoadResponse);
		ICollectionLoadResponse Nontable52Select(Guid? EsigRowpointer, int? Counter, string OperNum);
		void Nontable52Insert(ICollectionLoadResponse nonTable52LoadResponse);
		ICollectionLoadResponse Nontable53Select(Guid? EsigRowpointer, int? Counter, string WC);
		void Nontable53Insert(ICollectionLoadResponse nonTable53LoadResponse);
		ICollectionLoadResponse Nontable54Select(Guid? EsigRowpointer, int? Counter, string WCDescription);
		void Nontable54Insert(ICollectionLoadResponse nonTable54LoadResponse);
		ICollectionLoadResponse Nontable55Select(Guid? EsigRowpointer, int? Counter, string EffectDate);
		void Nontable55Insert(ICollectionLoadResponse nonTable55LoadResponse);
		ICollectionLoadResponse Nontable56Select(Guid? EsigRowpointer, int? Counter, string ObsDate);
		void Nontable56Insert(ICollectionLoadResponse nonTable56LoadResponse);
		ICollectionLoadResponse Nontable57Select(Guid? EsigRowpointer, int? Counter, string SpecificNoteDesc);
		void Nontable57Insert(ICollectionLoadResponse nonTable57LoadResponse);
		ICollectionLoadResponse Nontable58Select(Guid? EsigRowpointer, int? Counter, string SpecificNoteContent);
		void Nontable58Insert(ICollectionLoadResponse nonTable58LoadResponse);
		ICollectionLoadResponse Nontable59Select(Guid? EsigRowpointer, int? Counter, string MatlItem);
		void Nontable59Insert(ICollectionLoadResponse nonTable59LoadResponse);
		ICollectionLoadResponse Nontable60Select(Guid? EsigRowpointer, int? Counter, string MatlDescription);
		void Nontable60Insert(ICollectionLoadResponse nonTable60LoadResponse);
		ICollectionLoadResponse Nontable61Select(Guid? EsigRowpointer, int? Counter, string AltGroup);
		void Nontable61Insert(ICollectionLoadResponse nonTable61LoadResponse);
		ICollectionLoadResponse Nontable62Select(Guid? EsigRowpointer, int? Counter, string AltGroupRank);
		void Nontable62Insert(ICollectionLoadResponse nonTable62LoadResponse);
		ICollectionLoadResponse Nontable63Select(Guid? EsigRowpointer, int? Counter, string Sequence);
		void Nontable63Insert(ICollectionLoadResponse nonTable63LoadResponse);
		ICollectionLoadResponse Nontable64Select(Guid? EsigRowpointer, int? Counter, string MatlType);
		void Nontable64Insert(ICollectionLoadResponse nonTable64LoadResponse);
		ICollectionLoadResponse Nontable65Select(Guid? EsigRowpointer, int? Counter, string MatlQtyConv);
		void Nontable65Insert(ICollectionLoadResponse nonTable65LoadResponse);
		ICollectionLoadResponse Nontable66Select(Guid? EsigRowpointer, int? Counter, string Units);
		void Nontable66Insert(ICollectionLoadResponse nonTable66LoadResponse);
		ICollectionLoadResponse Nontable67Select(Guid? EsigRowpointer, int? Counter, string UM);
		void Nontable67Insert(ICollectionLoadResponse nonTable67LoadResponse);
		ICollectionLoadResponse Nontable68Select(Guid? EsigRowpointer, int? Counter, string BOMSeq);
		void Nontable68Insert(ICollectionLoadResponse nonTable68LoadResponse);
		ICollectionLoadResponse Nontable69Select(Guid? EsigRowpointer, int? Counter, string Feature);
		void Nontable69Insert(ICollectionLoadResponse nonTable69LoadResponse);
		ICollectionLoadResponse Nontable70Select(Guid? EsigRowpointer, int? Counter, string FeatureDescription);
		void Nontable70Insert(ICollectionLoadResponse nonTable70LoadResponse);
		ICollectionLoadResponse Nontable71Select(Guid? EsigRowpointer, int? Counter, string OptCode);
		void Nontable71Insert(ICollectionLoadResponse nonTable71LoadResponse);
		ICollectionLoadResponse Nontable72Select(Guid? EsigRowpointer, int? Counter, string Probable);
		void Nontable72Insert(ICollectionLoadResponse nonTable72LoadResponse);
		ICollectionLoadResponse Nontable73Select(Guid? EsigRowpointer, int? Counter, string IncPrice);
		void Nontable73Insert(ICollectionLoadResponse nonTable73LoadResponse);
		ICollectionLoadResponse Nontable74Select(Guid? EsigRowpointer, int? Counter, string MatlCostConv);
		void Nontable74Insert(ICollectionLoadResponse nonTable74LoadResponse);
		ICollectionLoadResponse Nontable75Select(Guid? EsigRowpointer, int? Counter, string LbrCostConv);
		void Nontable75Insert(ICollectionLoadResponse nonTable75LoadResponse);
		ICollectionLoadResponse Nontable76Select(Guid? EsigRowpointer, int? Counter, string FovhdCostConv);
		void Nontable76Insert(ICollectionLoadResponse nonTable76LoadResponse);
		ICollectionLoadResponse Nontable77Select(Guid? EsigRowpointer, int? Counter, string VovhdCostConv);
		void Nontable77Insert(ICollectionLoadResponse nonTable77LoadResponse);
		ICollectionLoadResponse Nontable78Select(Guid? EsigRowpointer, int? Counter, string OutCostConv);
		void Nontable78Insert(ICollectionLoadResponse nonTable78LoadResponse);
		ICollectionLoadResponse Nontable79Select(Guid? EsigRowpointer, int? Counter, string CostConv);
		void Nontable79Insert(ICollectionLoadResponse nonTable79LoadResponse);
		ICollectionLoadResponse Nontable80Select(Guid? EsigRowpointer, int? Counter, string EcnLine);
		void Nontable80Insert(ICollectionLoadResponse nonTable80LoadResponse);
		ICollectionLoadResponse Nontable81Select(Guid? EsigRowpointer, int? Counter, string Job);
		void Nontable81Insert(ICollectionLoadResponse nonTable81LoadResponse);
		ICollectionLoadResponse Nontable82Select(Guid? EsigRowpointer, int? Counter, string Suffix);
		void Nontable82Insert(ICollectionLoadResponse nonTable82LoadResponse);
		ICollectionLoadResponse Nontable83Select(Guid? EsigRowpointer, int? Counter, string ECNItemType);
		void Nontable83Insert(ICollectionLoadResponse nonTable83LoadResponse);
		ICollectionLoadResponse Nontable84Select(Guid? EsigRowpointer, int? Counter, string ActionCode);
		void Nontable84Insert(ICollectionLoadResponse nonTable84LoadResponse);
		ICollectionLoadResponse Nontable85Select(Guid? EsigRowpointer, int? Counter, string EcniGroup);
		void Nontable85Insert(ICollectionLoadResponse nonTable85LoadResponse);
		ICollectionLoadResponse Nontable86Select(Guid? EsigRowpointer, int? Counter, string Item);
		void Nontable86Insert(ICollectionLoadResponse nonTable86LoadResponse);
		ICollectionLoadResponse Nontable87Select(Guid? EsigRowpointer, int? Counter, string ItemDescription);
		void Nontable87Insert(ICollectionLoadResponse nonTable87LoadResponse);
		ICollectionLoadResponse Nontable88Select(Guid? EsigRowpointer, int? Counter, string ItemStat);
		void Nontable88Insert(ICollectionLoadResponse nonTable88LoadResponse);
		ICollectionLoadResponse Nontable89Select(Guid? EsigRowpointer, int? Counter, string Revision);
		void Nontable89Insert(ICollectionLoadResponse nonTable89LoadResponse);
		ICollectionLoadResponse Nontable90Select(Guid? EsigRowpointer, int? Counter, string OperNum);
		void Nontable90Insert(ICollectionLoadResponse nonTable90LoadResponse);
		ICollectionLoadResponse Nontable91Select(Guid? EsigRowpointer, int? Counter, string WC);
		void Nontable91Insert(ICollectionLoadResponse nonTable91LoadResponse);
		ICollectionLoadResponse Nontable92Select(Guid? EsigRowpointer, int? Counter, string WCDescription);
		void Nontable92Insert(ICollectionLoadResponse nonTable92LoadResponse);
		ICollectionLoadResponse Nontable93Select(Guid? EsigRowpointer, int? Counter, string SpecificNoteDesc);
		void Nontable93Insert(ICollectionLoadResponse nonTable93LoadResponse);
		ICollectionLoadResponse Nontable94Select(Guid? EsigRowpointer, int? Counter, string SpecificNoteContent);
		void Nontable94Insert(ICollectionLoadResponse nonTable94LoadResponse);
		ICollectionLoadResponse Nontable95Select(Guid? EsigRowpointer, int? Counter, string MatlItem);
		void Nontable95Insert(ICollectionLoadResponse nonTable95LoadResponse);
		ICollectionLoadResponse Nontable96Select(Guid? EsigRowpointer, int? Counter, string MatlDescription);
		void Nontable96Insert(ICollectionLoadResponse nonTable96LoadResponse);
		ICollectionLoadResponse Nontable97Select(Guid? EsigRowpointer, int? Counter, string Sequence);
		void Nontable97Insert(ICollectionLoadResponse nonTable97LoadResponse);
		ICollectionLoadResponse Nontable98Select(Guid? EsigRowpointer, int? Counter, string RefSeq);
		void Nontable98Insert(ICollectionLoadResponse nonTable98LoadResponse);
		ICollectionLoadResponse Nontable99Select(Guid? EsigRowpointer, int? Counter, string Bubble);
		void Nontable99Insert(ICollectionLoadResponse nonTable99LoadResponse);
		ICollectionLoadResponse Nontable100Select(Guid? EsigRowpointer, int? Counter, string RefDes);
		void Nontable100Insert(ICollectionLoadResponse nonTable100LoadResponse);
		ICollectionLoadResponse Nontable101Select(Guid? EsigRowpointer, int? Counter, string AssySeq);
		void Nontable101Insert(ICollectionLoadResponse nonTable101LoadResponse);
		(int? ReturnCode, Guid? EsigRowpointer) AltExtGen_CreateEcnEsigSp(string AltExtGenSp, string UserName, string ReasonCode, string ECNNum, Guid? EsigRowpointer);
	}
}

