using System;
using System.Runtime.InteropServices;

namespace CSI.ExternalContracts.FactoryTrack
{
    public interface IExtFTSLItemLocs
    {
        int ContainerMvPostSp(string ContainNum, string PType, DateTime? PDate, string FromWhse, string ToWhse, string ToLoc, byte? PZeroCost, string PStat, ref string Infobar);
        int IaPostSetVarsSp(string SET, string TrxType, DateTime? TransDate,  string Acct,  string AcctUnit1,  string AcctUnit2,  string AcctUnit3,  string AcctUnit4, decimal? TransQty, string Whse, string Item, string Loc,  string Lot,  string FromSite,  string ToSite,  string ReasonCode,  string TrnNum,  short? TrnLine,  decimal? TransNum,  decimal? RsvdNum, [DefaultParameterValue("I")] string SerialStat,  string Workkey, [DefaultParameterValue((byte)0)] byte? Override,  ref decimal? MatlCost,  ref decimal? LbrCost,  ref decimal? FovhdCost,  ref decimal? VovhdCost,  ref decimal? OutCost,  ref decimal? TotalCost,  ref decimal? ProfitMarkup, ref string Infobar,  string ToWhse,  string ToLoc,  string ToLot,  string TransferTrxType,  Guid? TmpSerId,  byte? UseExistingSerials,  string SerialPrefix,  string RemoteSiteLot,  string DocumentNum,  string ImportDocId, [DefaultParameterValue((byte)0)] byte? MoveZeroCostItem,  string EmpNum, [DefaultParameterValue((byte)0)] byte? SkipItemlocDelete,  DateTime? FromSiteRecordDate,  DateTime? ToSiteRecordDate);
        int ItemLocAddRemoteSp(string Whse, string Item, string Loc, byte? UcFlag, decimal? UnitCost, decimal? MatlCost, decimal? LbrCost, decimal? FovhdCost, decimal? VovhdCost, decimal? OutCost, byte? SetPermFlag,  string Site, ref Guid? RowPointer, ref string Infobar);
        int ItemLocAddSp(string Whse, string Item, string Loc, byte? UcFlag, decimal? UnitCost, decimal? MatlCost, decimal? LbrCost, decimal? FovhdCost, decimal? VovhdCost, decimal? OutCost, [DefaultParameterValue((byte)0)] byte? SetPermFlag, ref Guid? RowPointer, ref string Infobar,  byte? PermFlagValue,  byte? MrbFlagValue,  byte? locMrbFlag,  string locLocType,  string locWC);
        int ItemlocValidateSp(string Item, string Whse, string Loc, [DefaultParameterValue((byte)0)] byte? VerifyAccounts, [DefaultParameterValue((byte)0)] byte? CheckUserAccount,  string UserAcct, ref string Infobar,  ref string Prompt,  ref string PromptButtons, [DefaultParameterValue((byte)1)] byte? Outgoing,  ref decimal? ItemQtyOnHand,  string OldLoc,  string CoNum,  short? CoLine,  short? CoRelease,  string Lot);
        int ItemQtyDetlSp(string Site, string Type, string WhseType, string Whse, string Item, string Loc, string Lot, decimal? DeltaQty, int? Return, string Action, string TrnNum, int? TrnLine, decimal? TransNum, decimal? RsvdNum, string Stat, int? Byprod, string Workkey, ref string PromptMsg, ref string PromptButtons, ref string Infobar,  string ImportDocId, [DefaultParameterValue(0)] ref int? CallForm);
        int PostAdjTransWrapperSp(string TrxType, DateTime? TransDate,  string Acct,  string AcctUnit1,  string AcctUnit2,  string AcctUnit3,  string AcctUnit4, decimal? TransQty, string Whse, string Item, string Loc,  string Lot,  string FromSite,  string ToSite,  string ReasonCode,  string TrnNum,  short? TrnLine,  decimal? TransNum,  decimal? RsvdNum, [DefaultParameterValue("I")] string SerialStat,  string Workkey, [DefaultParameterValue((byte)0)] byte? Override,  ref decimal? MatlCost,  ref decimal? LbrCost,  ref decimal? FovhdCost,  ref decimal? VovhdCost,  ref decimal? OutCost,  ref decimal? TotalCost,  ref decimal? ProfitMarkup, ref string Infobar,  string ToWhse,  string ToLoc,  string ToLot,  string TransferTrxType,  Guid? TmpSerId,  byte? UseExistingSerials,  string SerialPrefix,  string RemoteSiteLot,  string DocumentNum,  string ImportDocId, [DefaultParameterValue((byte)0)] byte? MoveZeroCostItem, [DefaultParameterValue(0)] int? DropDeferred,  ref string PromptMsg,  ref string PromptButtons);
        int SlocValidSp(string Item, string Whse, string Loc, ref string Lot, ref string Infobar, ref string ImportDocId);
    }
}