using System;
using System.Runtime.InteropServices;

namespace CSI.ExternalContracts.FactoryTrack
{
    public interface IExtFTSLJobTrans
    {
        int ApsSyncDeferSetVarsSp(string SET, ref string Infobar);
        int ApsSyncImmediateSetVarsSp(string SET, ref string Infobar, [DefaultParameterValue(0)] int? DropDeferred);
        int CheckSerialSp(string PSerNum, string PItem, ref string Infobar);
        int GetItemByJobSp(string pJob, short? pSuffix, ref string pItem, ref string pDescription, ref byte? pSerialTracked, ref byte? pLotTracked, ref string pLotPrefix, ref string Infobar, ref string pSerialPrefix, ref byte? pCostCode, ref byte? pPeassignSerials, ref byte? pPreassignLots, ref byte? pParentJobPeassignSerials, ref byte? pParentJobPreassignLots);
        int JobBookingCheckSp(string pJob, short? pSuffix, int? pOperNum, byte? pComplete, decimal? pQtyComplete, decimal? pQtyScrapped, byte? pHasLoc, ref string Infobar);
        int JobJobP(byte PostComplete, byte PostNegativeInventory, string StartJob, string EndJob, short? StartSuffix, short? EndSuffix, DateTime? StartTranDate, DateTime? EndTranDate, string StartEmpNum, string EndEmpNum, string StartDept, string EndDept, string StartShift, string EndShift, string StartUserCode, string EndUserCode, string ValidEmpTypes, string CurWhse, short? StartTranDateOffset, short? EndTranDateOffset, ref string Infobar, ref string PromptButtons, string Wc, string DocumentNum);
        int JobtranCalcRateSp(string InPayRate, string InEmpNum, string InShift, DateTime? InTransDate, ref decimal? OutPrRate, ref decimal? OutJobRate);
        int JobtranEmpValidSp(string EmpNum, string PayRate, DateTime? TransDate, ref string OutShift, ref string OutEmpName, ref decimal? OutPrRate, ref decimal? OutJobRate, ref string PromptMsg, ref string PromptButtons);
        int JobtranJobValidSp(string TransType, string InJob, string OldJob, ref short? InSuffix, short? OldSuffix, int? InOperNum, string JobOfPreviousRecord, ref byte? JobCoProdMix, ref string JobOrdType, ref string JobItem, ref byte? ItemLotTracked, ref byte? ItemSerialTracked, ref string ItemDesc, ref string ItemUm, ref string JobWhse, ref string JobRootJob, ref short? JobRootSuf, ref string JobRefJob, ref string JobStat, ref string JobJobType, ref byte? CntrlPoint, ref string Wc, ref string WcDesc, ref int? OperNum, ref int? NextOper, ref string NextWc, ref string NextWcDesc, ref byte? OperComplete, ref string Location, ref string LocDesc, ref byte? PIssueParent, ref string PProjNum, ref int? PTaskNum, ref int? PSeq, ref string PromptMsg, ref string PromptButtons, ref string Infobar, ref byte? JobPreassignLots, ref byte? JobPreassignSerials, ref string ItemLotPrefix, ref string ItemSerialPrefix, ref byte? Rework,  ref short? JobRefSuf,  ref byte? JobpPreassignLots,  ref byte? JobpPreassignSerials, [DefaultParameterValue((byte)0)] byte? AllOperComplete,  string OldTransType,  ref string NewOldJob);
        int JobtranLotValidSp(string InLot, string InItem, string RefNum, short? RefLine, string RefType, ref string OutLot, ref byte? AddQuestionAsked, ref byte? ContQuestionAsked, ref string PromptMsg, ref string PromptButtons, ref string Infobar,  byte? PreassignLots, [DefaultParameterValue(0)] decimal? Quantity,  ref string TrxRestrictCode);
        int JobtranOperNumValidSp(string TransType, string InJob, short? InSuffix, int? InOperNum, ref int? OldOperNum, ref byte? CntrlPoint, ref string Wc, ref string WcDesc, ref string CostCode, ref int? NextOper, ref string NextWc, ref string NextWcDesc, ref string Loc, ref string LocDesc, ref byte? OperComplete, ref string PromptMsg, ref string PromptButtons, ref string Infobar, ref decimal? JobQtyPerSheet);
        int JobtranQtyCompleteValidSp(string InJob, short? InSuffix, int? InOperNum, decimal? InQtyComplete, ref string PromptMsg, ref string PromptButtons);
        int JobWipTransPost(Guid SessionID, long TransNum, byte Coby, ref string Infobar);
        int JustInTimeGenerateTransNumSp(Guid? SessionID, ref decimal? TJobtranTransNum, ref string Infobar);
        int JustInTimeTransactionSp(string TItem, decimal? TcQtuQty, string TWhse, string TLoc, string TLot, DateTime? TTransDate, string TShift, string TEmpNum, int? PPostNeg, string SerialPrefix, Guid? SessionID, ref string Infobar,  string ContainerNum,  string DocumentNum);
        int PostWcLaborSp(string pWc, string pEmpNum, decimal? pAHrs, int? pStartTime, int? pEndTime, string pShift, DateTime? pTransDate, Guid? SessionID, ref decimal? SJobtranTransNum, ref byte? tCoby, ref string Infobar,  string DocumentNum);
        int ProcessJobMatlTransSetVarsSp(string SET, string Job, short? Suffix, int? OperNum, short? Sequence, [DefaultParameterValue((byte)0)] byte? DeleteTmpSer, [DefaultParameterValue((byte)0)] byte? Backflush, [DefaultParameterValue((byte)0)] byte? ByProduct,  string UM, string Item,  string Description,  string Wc, string Whse,  string Loc,  string Lot, DateTime? TransDate, decimal? MatlCost, decimal? LbrCost, decimal? FovhdCost, decimal? VovhdCost, decimal? OutCost, decimal? Cost,  decimal? PlanCost, decimal? Qty,  string Acct,  string AcctUnit1,  string AcctUnit2,  string AcctUnit3,  string AcctUnit4,  Guid? RowPointer, string JobmatlRefType, string JobmatlRefNum, short? JobmatlRefLineSuf, short? JobmatlRefRelease, ref string Infobar, string ImportDocId, string JobLot, string JobSerial, string ContainerNum, DateTime? RecordDate,  string EmpNum,  string DocumentNum);
        int ProcessJobMatlTransSp(string Job, short? Suffix, int? OperNum, short? Sequence, [DefaultParameterValue((byte)0)] byte? DeleteTmpSer, [DefaultParameterValue((byte)0)] byte? Backflush, [DefaultParameterValue((byte)0)] byte? ByProduct,  string UM, string Item,  string Description,  string Wc, string Whse,  string Loc,  string Lot, DateTime? TransDate, decimal? MatlCost, decimal? LbrCost, decimal? FovhdCost, decimal? VovhdCost, decimal? OutCost, decimal? Cost,  decimal? PlanCost, decimal? Qty,  string Acct,  string AcctUnit1,  string AcctUnit2,  string AcctUnit3,  string AcctUnit4,  Guid? RowPointer, string JobmatlRefType, string JobmatlRefNum, short? JobmatlRefLineSuf, short? JobmatlRefRelease, ref string Infobar, string ImportDocId,  string JobLot,  string JobSerial,  string ContainerNum,  DateTime? RecordDate,  string EmpNum,  string DocumentNum);
        int PSCmplTransPost(Guid SessionID, long? TransNum, string Coby, ref string Infobar);
        int PSGenerateTransNumSp(Guid? SessionID, ref decimal? TJobtranTransNum, ref string Infobar);
        int PSScrapTransPost(Guid SessionID, long TransNum, byte Coby, ref string Infobar);
        int SetIssueParentSp(string PJob, short? PSuffix, ref byte? PIssueParent, ref string PProjNum, ref int? PTaskNum, ref int? PSeq, ref string Infobar);
    }
}