
using System;
using System.Collections.Generic;
using System.Text;
using System.Runtime.InteropServices;

namespace CSI.ExternalContracts.FactoryTrack
{
    public interface IExtFTSLProjMatls
    {

        int PmatlValidateMatlQtySp(decimal? NewMatlQty,
                string PWhse,
                string PItem,
                string PLoc,
                string PLot,
                double? UomConvFactor,
                decimal? QtyIssuedConv,
                decimal? QtyRequiredConv,
                byte? CreateMatl,
                ref decimal? TQty,
                ref string PromptButtons,
                ref string PromptMsg,
                ref string Infobar,
                string PImportDocId,
                [Optional] string ProjNum,
                [Optional] int? TaskNum,
                [Optional] int? ProjmatSeq,
                [Optional] ref decimal? ConsignQtyRequired,
                [Optional] ref string ConsignVdrWhse,
                [Optional] ref string ConsignVdrLoc,
                [Optional] ref string ConsignedPromptButtons,
                [Optional] ref string ConsignedPromptMsg,
                [Optional] ref string ContianedPromptButtons,
                [Optional] ref string ContianedPromptMsg,
                [Optional] ref string CallFormStr); 

        int prjresValidateItemSp(ref string PItem,
                string POldItem,
                string PProj,
                byte? PAddMode,
                ref decimal? PCost,
                ref byte? PBackflush,
                ref string PRefType,
                ref string PMatlType,
                ref string PUnits,
                ref decimal? PMatlCost,
                ref decimal? PLbrCost,
                ref decimal? PFovhdCost,
                ref decimal? PVovhdCost,
                ref decimal? POutCost,
                ref decimal? PFmatlovhd,
                ref decimal? PVmatlovhd,
                ref string PUM,
                ref byte? PItemAvail,
                ref string PItemDesc,
                ref byte? PItemSerialTracked,
                ref string PCostCode,
                ref string Infobar,
                [Optional] ref string Prompt,
                [Optional] ref string PromptButtons,
                [Optional, DefaultParameterValue((byte)0)] ref byte? SupplQtyReq,
                [Optional, DefaultParameterValue(1)] ref double? SupplQtyConvFactor,
                [Optional] ref string Origin,
                [Optional] ref string CommCode,
                [Optional, DefaultParameterValue(0)] ref decimal? UnitWeight,
                ref byte? Kit); 

        int ProjmatlTransactionByContainerSp(string ContainerNum,
                [Optional] string PProjNum,
                [Optional] int? PTaskNum,
                string CurWhse,
                DateTime? PTransDate,
                ref string PromptMsg,
                ref string PromptButtons,
                ref string Infobar); 

        int ProjmatlTransactionSetVarsSp(string SET,
                string PProjNum,
                int? PTaskNum,
                int? PSeqNum,
                string PItem,
                string PItemDesc,
                decimal? PQty,
                decimal? PQtyConv,
                string PUM,
                string CurWhse,
                string PCostCode,
                string PLoc1,
                string PLot1,
                DateTime? PTransDate,
                string PTranType,
                string PNonInvAcct,
                string PNonInvAcctUnit1,
                string PNonInvAcctUnit2,
                string PNonInvAcctUnit3,
                string PNonInvAcctUnit4,
                decimal? PNonInvCost,
                int? CreateMatl,
                ref int? TSeqNum,
                ref string Infobar,
                string PImportDocId1,
                [Optional] string DocumentNum); 

        int ProjmatlValidateItemSp(string Item,
                string ProjNum,
                int? TaskNum,
                int? SeqNum,
                string Whse,
                ref string TItem,
                ref int? TSeqNum,
                ref string TItemDesc,
                ref int? TSerTracked,
                ref int? TLotTracked,
                ref string TNonInvAcct,
                ref decimal? TNonInvCost,
                ref string TCostCode,
                ref string TLoc,
                ref string TLot,
                ref decimal? TRequired,
                ref decimal? TIssued,
                ref decimal? TOnHand,
                ref string TUM,
                ref decimal? UomConvFactor,
                ref decimal? TRequiredConv,
                ref decimal? TIssuedConv,
                ref decimal? TOnHandConv,
                ref decimal? TQty,
                ref decimal? TQtyConv,
                ref int? ItemAvailable,
                ref string PromptMsg1,
                ref string PromptButtons1,
                ref string PromptMsg2,
                ref string PromptButtons2,
                ref string Infobar,
                ref string TImportDocId,
                ref int? TTaxFreeMatl,
                ref int? TTrackPieces,
                ref string TDimensionGroup,
                ref decimal? TQtyShipped,
                ref int? IsControl,
                ref int? ItemTrackECN,
                ref string Revision); 

        int ProjmatlValidateLocSp(string Item,
                string ProjNum,
                int? TaskNum,
                int? SeqNum,
                string Whse,
                string TLoc,
                double? UomConvFactor,
                ref string TLot,
                ref decimal? TOnHand,
                ref decimal? TOnHandConv,
                ref decimal? TQty,
                ref decimal? TQtyConv,
                ref string Infobar,
                ref string TImportDocId); 

    }
}
    
