//PROJECT NAME: Logistics
//CLASS NAME: SSSFSSchedLabelsINIT.cs

using CSI.Data.SQL.UDDT;
using System;
using System.Data;
using CSI.Data.CRUD;
using CSI.Data.RecordSets;
using CSI.MG;

namespace CSI.Logistics.FieldService.Partner
{
	public interface ISSSFSSchedLabelsINIT
	{
		(int? ReturnCode, string ReferenceLabel, string ReferenceValue, string ReferenceEnter, string PartnerIDLabel, string PartnerIDValue, string PartnerIDEnter, string PartnerNameLabel, string PartnerNameValue, string PartnerNameEnter, string DescriptionLabel, string DescriptionValue, string DescriptionEnter, string ApptStatusLabel, string ApptStatusValue, string ApptStatusEnter, string RefStatusLabel, string RefStatusValue, string RefStatusEnter, string PriorityLabel, string PriorityValue, string PriorityEnter, string CustNameLabel, string CustNameValue, string CustNameEnter, string SROTypeLabel, string SROTypeValue, string SROTypeEnter, string ApptDateTimeLabel, string ApptDateTimeValue, string ApptDateTimeEnter, string ApptHoursLabel, string ApptHoursValue, string ApptHoursEnter, string TerritoryRegionLabel, string TerritoryRegionValue, string TerritoryRegionEnter) SSSFSSchedLabelsINITSp(string UserName,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string SechID,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string ReferenceLabel,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string ReferenceValue,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string ReferenceEnter,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string PartnerIDLabel,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string PartnerIDValue,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string PartnerIDEnter,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string PartnerNameLabel,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string PartnerNameValue,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string PartnerNameEnter,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string DescriptionLabel,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string DescriptionValue,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string DescriptionEnter,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string ApptStatusLabel,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string ApptStatusValue,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string ApptStatusEnter,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string RefStatusLabel,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string RefStatusValue,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string RefStatusEnter,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string PriorityLabel,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string PriorityValue,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string PriorityEnter,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string CustNameLabel,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string CustNameValue,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string CustNameEnter,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string SROTypeLabel,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string SROTypeValue,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string SROTypeEnter,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string ApptDateTimeLabel,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string ApptDateTimeValue,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string ApptDateTimeEnter,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string ApptHoursLabel,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string ApptHoursValue,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string ApptHoursEnter,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string TerritoryRegionLabel,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string TerritoryRegionValue,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   string TerritoryRegionEnter);
	}
	
	public class SSSFSSchedLabelsINIT : ISSSFSSchedLabelsINIT
	{
		IApplicationDB appDB;
		
		public SSSFSSchedLabelsINIT(IApplicationDB appDB)
		{
			this.appDB = appDB;
		}
		
		public (int? ReturnCode, string ReferenceLabel, string ReferenceValue, string ReferenceEnter, string PartnerIDLabel, string PartnerIDValue, string PartnerIDEnter, string PartnerNameLabel, string PartnerNameValue, string PartnerNameEnter, string DescriptionLabel, string DescriptionValue, string DescriptionEnter, string ApptStatusLabel, string ApptStatusValue, string ApptStatusEnter, string RefStatusLabel, string RefStatusValue, string RefStatusEnter, string PriorityLabel, string PriorityValue, string PriorityEnter, string CustNameLabel, string CustNameValue, string CustNameEnter, string SROTypeLabel, string SROTypeValue, string SROTypeEnter, string ApptDateTimeLabel, string ApptDateTimeValue, string ApptDateTimeEnter, string ApptHoursLabel, string ApptHoursValue, string ApptHoursEnter, string TerritoryRegionLabel, string TerritoryRegionValue, string TerritoryRegionEnter) SSSFSSchedLabelsINITSp(string UserName,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string SechID,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string ReferenceLabel,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string ReferenceValue,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string ReferenceEnter,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string PartnerIDLabel,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string PartnerIDValue,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string PartnerIDEnter,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string PartnerNameLabel,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string PartnerNameValue,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string PartnerNameEnter,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string DescriptionLabel,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string DescriptionValue,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string DescriptionEnter,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string ApptStatusLabel,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string ApptStatusValue,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string ApptStatusEnter,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string RefStatusLabel,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string RefStatusValue,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string RefStatusEnter,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string PriorityLabel,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string PriorityValue,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string PriorityEnter,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string CustNameLabel,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string CustNameValue,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string CustNameEnter,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string SROTypeLabel,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string SROTypeValue,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string SROTypeEnter,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string ApptDateTimeLabel,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string ApptDateTimeValue,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string ApptDateTimeEnter,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string ApptHoursLabel,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string ApptHoursValue,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string ApptHoursEnter,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string TerritoryRegionLabel,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string TerritoryRegionValue,
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          string TerritoryRegionEnter)
		{
			UsernameType _UserName = UserName;
			StringType _SechID = SechID;
			BolNumType _ReferenceLabel = ReferenceLabel;
			BolNumType _ReferenceValue = ReferenceValue;
			BolNumType _ReferenceEnter = ReferenceEnter;
			BolNumType _PartnerIDLabel = PartnerIDLabel;
			BolNumType _PartnerIDValue = PartnerIDValue;
			BolNumType _PartnerIDEnter = PartnerIDEnter;
			BolNumType _PartnerNameLabel = PartnerNameLabel;
			BolNumType _PartnerNameValue = PartnerNameValue;
			BolNumType _PartnerNameEnter = PartnerNameEnter;
			BolNumType _DescriptionLabel = DescriptionLabel;
			BolNumType _DescriptionValue = DescriptionValue;
			BolNumType _DescriptionEnter = DescriptionEnter;
			BolNumType _ApptStatusLabel = ApptStatusLabel;
			BolNumType _ApptStatusValue = ApptStatusValue;
			BolNumType _ApptStatusEnter = ApptStatusEnter;
			BolNumType _RefStatusLabel = RefStatusLabel;
			BolNumType _RefStatusValue = RefStatusValue;
			BolNumType _RefStatusEnter = RefStatusEnter;
			BolNumType _PriorityLabel = PriorityLabel;
			BolNumType _PriorityValue = PriorityValue;
			BolNumType _PriorityEnter = PriorityEnter;
			BolNumType _CustNameLabel = CustNameLabel;
			BolNumType _CustNameValue = CustNameValue;
			BolNumType _CustNameEnter = CustNameEnter;
			BolNumType _SROTypeLabel = SROTypeLabel;
			BolNumType _SROTypeValue = SROTypeValue;
			BolNumType _SROTypeEnter = SROTypeEnter;
			BolNumType _ApptDateTimeLabel = ApptDateTimeLabel;
			BolNumType _ApptDateTimeValue = ApptDateTimeValue;
			BolNumType _ApptDateTimeEnter = ApptDateTimeEnter;
			BolNumType _ApptHoursLabel = ApptHoursLabel;
			BolNumType _ApptHoursValue = ApptHoursValue;
			BolNumType _ApptHoursEnter = ApptHoursEnter;
			BolNumType _TerritoryRegionLabel = TerritoryRegionLabel;
			BolNumType _TerritoryRegionValue = TerritoryRegionValue;
			BolNumType _TerritoryRegionEnter = TerritoryRegionEnter;
			
			using (IDbCommand cmd = appDB.CreateCommand())
			{
				
				cmd.CommandType = CommandType.StoredProcedure;
				cmd.CommandText = "SSSFSSchedLabelsINITSp";
				
				appDB.AddCommandParameter(cmd, "UserName", _UserName, ParameterDirection.Input);
				appDB.AddCommandParameter(cmd, "SechID", _SechID, ParameterDirection.Input);
				appDB.AddCommandParameter(cmd, "ReferenceLabel", _ReferenceLabel, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "ReferenceValue", _ReferenceValue, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "ReferenceEnter", _ReferenceEnter, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "PartnerIDLabel", _PartnerIDLabel, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "PartnerIDValue", _PartnerIDValue, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "PartnerIDEnter", _PartnerIDEnter, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "PartnerNameLabel", _PartnerNameLabel, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "PartnerNameValue", _PartnerNameValue, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "PartnerNameEnter", _PartnerNameEnter, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "DescriptionLabel", _DescriptionLabel, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "DescriptionValue", _DescriptionValue, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "DescriptionEnter", _DescriptionEnter, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "ApptStatusLabel", _ApptStatusLabel, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "ApptStatusValue", _ApptStatusValue, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "ApptStatusEnter", _ApptStatusEnter, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "RefStatusLabel", _RefStatusLabel, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "RefStatusValue", _RefStatusValue, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "RefStatusEnter", _RefStatusEnter, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "PriorityLabel", _PriorityLabel, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "PriorityValue", _PriorityValue, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "PriorityEnter", _PriorityEnter, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "CustNameLabel", _CustNameLabel, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "CustNameValue", _CustNameValue, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "CustNameEnter", _CustNameEnter, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "SROTypeLabel", _SROTypeLabel, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "SROTypeValue", _SROTypeValue, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "SROTypeEnter", _SROTypeEnter, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "ApptDateTimeLabel", _ApptDateTimeLabel, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "ApptDateTimeValue", _ApptDateTimeValue, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "ApptDateTimeEnter", _ApptDateTimeEnter, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "ApptHoursLabel", _ApptHoursLabel, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "ApptHoursValue", _ApptHoursValue, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "ApptHoursEnter", _ApptHoursEnter, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "TerritoryRegionLabel", _TerritoryRegionLabel, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "TerritoryRegionValue", _TerritoryRegionValue, ParameterDirection.InputOutput);
				appDB.AddCommandParameter(cmd, "TerritoryRegionEnter", _TerritoryRegionEnter, ParameterDirection.InputOutput);
				
				var Severity = appDB.ExecuteNonQuery(cmd);
				
				ReferenceLabel = _ReferenceLabel;
				ReferenceValue = _ReferenceValue;
				ReferenceEnter = _ReferenceEnter;
				PartnerIDLabel = _PartnerIDLabel;
				PartnerIDValue = _PartnerIDValue;
				PartnerIDEnter = _PartnerIDEnter;
				PartnerNameLabel = _PartnerNameLabel;
				PartnerNameValue = _PartnerNameValue;
				PartnerNameEnter = _PartnerNameEnter;
				DescriptionLabel = _DescriptionLabel;
				DescriptionValue = _DescriptionValue;
				DescriptionEnter = _DescriptionEnter;
				ApptStatusLabel = _ApptStatusLabel;
				ApptStatusValue = _ApptStatusValue;
				ApptStatusEnter = _ApptStatusEnter;
				RefStatusLabel = _RefStatusLabel;
				RefStatusValue = _RefStatusValue;
				RefStatusEnter = _RefStatusEnter;
				PriorityLabel = _PriorityLabel;
				PriorityValue = _PriorityValue;
				PriorityEnter = _PriorityEnter;
				CustNameLabel = _CustNameLabel;
				CustNameValue = _CustNameValue;
				CustNameEnter = _CustNameEnter;
				SROTypeLabel = _SROTypeLabel;
				SROTypeValue = _SROTypeValue;
				SROTypeEnter = _SROTypeEnter;
				ApptDateTimeLabel = _ApptDateTimeLabel;
				ApptDateTimeValue = _ApptDateTimeValue;
				ApptDateTimeEnter = _ApptDateTimeEnter;
				ApptHoursLabel = _ApptHoursLabel;
				ApptHoursValue = _ApptHoursValue;
				ApptHoursEnter = _ApptHoursEnter;
				TerritoryRegionLabel = _TerritoryRegionLabel;
				TerritoryRegionValue = _TerritoryRegionValue;
				TerritoryRegionEnter = _TerritoryRegionEnter;
				
				return (Severity, ReferenceLabel, ReferenceValue, ReferenceEnter, PartnerIDLabel, PartnerIDValue, PartnerIDEnter, PartnerNameLabel, PartnerNameValue, PartnerNameEnter, DescriptionLabel, DescriptionValue, DescriptionEnter, ApptStatusLabel, ApptStatusValue, ApptStatusEnter, RefStatusLabel, RefStatusValue, RefStatusEnter, PriorityLabel, PriorityValue, PriorityEnter, CustNameLabel, CustNameValue, CustNameEnter, SROTypeLabel, SROTypeValue, SROTypeEnter, ApptDateTimeLabel, ApptDateTimeValue, ApptDateTimeEnter, ApptHoursLabel, ApptHoursValue, ApptHoursEnter, TerritoryRegionLabel, TerritoryRegionValue, TerritoryRegionEnter);
			}
		}
	}
}
