//PROJECT NAME: Material
//CLASS NAME: IGetTransferItemInfo.cs

using System;
using System.Data;
using CSI.Data.CRUD;
using CSI.Data.SQL.UDDT;

namespace CSI.Material
{
	public interface IGetTransferItemInfo
	{
		(int? ReturnCode, string Origin,
		decimal? UnitWeight,
		string UM,
		string ToRefType,
		string ToRefNum,
		int? ToRefLineSuf,
		int? ToRefRelease,
		string FrmRefType,
		string FrmRefNum,
		int? FrmRefLineSuf,
		int? FrmRefRelease,
		string TrnLoc,
		decimal? UnitCost,
		decimal? UnitCostConv,
		decimal? MatlCost,
		decimal? LbrCost,
		decimal? FovhdCost,
		decimal? VovhdCost,
		decimal? OutCost,
		decimal? UnitPrice,
		decimal? UnitPriceConv,
		decimal? UnitMatCost,
		decimal? UnitMatCostConv,
		decimal? UnitFreightCost,
		decimal? UnitFreightCostConv,
		decimal? UnitDutyCost,
		decimal? UnitDutyCostConv,
		decimal? UnitBrokerageCost,
		decimal? UnitBrokerageCostConv,
		decimal? UnitInsuranceCost,
		decimal? UnitInsuranceCostConv,
		decimal? UnitLocFrtCost,
		decimal? UnitLocFrtCostConv,
		decimal? UnitTotalCost,
		decimal? ExtPrice,
		string CommCode,
		int? SupplQtyReq,
		decimal? SupplQtyConvFactor,
		string Infobar,
		int? FromLotTrack,
		int? ToLotTrack,
		int? PreassignLots,
		int? FromSerialTrack,
		int? ToSerialTrack,
		int? PreassignSerials,
		string ToLotPrefix,
		string ToSerialPrefix,
		int? UseExistingLot,
		int? UseExistingSerial) GetTransferItemInfoSp(string TrnNum,
		string Item,
		string Pricecode,
		decimal? QtyReq,
		int? Update,
		int? TrnLine,
		string FromSite,
		string ToSite,
		string Origin,
		decimal? UnitWeight,
		string UM,
		string ToRefType,
		string ToRefNum,
		int? ToRefLineSuf,
		int? ToRefRelease,
		string FrmRefType,
		string FrmRefNum,
		int? FrmRefLineSuf,
		int? FrmRefRelease,
		string TrnLoc,
		decimal? UnitCost,
		decimal? UnitCostConv,
		decimal? MatlCost,
		decimal? LbrCost,
		decimal? FovhdCost,
		decimal? VovhdCost,
		decimal? OutCost,
		decimal? UnitPrice,
		decimal? UnitPriceConv,
		decimal? UnitMatCost,
		decimal? UnitMatCostConv,
		decimal? UnitFreightCost,
		decimal? UnitFreightCostConv,
		decimal? UnitDutyCost,
		decimal? UnitDutyCostConv,
		decimal? UnitBrokerageCost,
		decimal? UnitBrokerageCostConv,
		decimal? UnitInsuranceCost,
		decimal? UnitInsuranceCostConv,
		decimal? UnitLocFrtCost,
		decimal? UnitLocFrtCostConv,
		decimal? UnitTotalCost,
		decimal? ExtPrice,
		string CommCode,
		int? SupplQtyReq,
		decimal? SupplQtyConvFactor,
		string Infobar,
		int? FromLotTrack,
		int? ToLotTrack,
		int? PreassignLots,
		int? FromSerialTrack,
		int? ToSerialTrack,
		int? PreassignSerials,
		string ToLotPrefix,
		string ToSerialPrefix,
		int? UseExistingLot,
		int? UseExistingSerial);
	}
}

