//PROJECT NAME: Material
//CLASS NAME: IItemInsUpdRemCall.cs

using System;
using System.Data;
using CSI.Data.CRUD;
using CSI.Data.SQL.UDDT;

namespace CSI.Material
{
	public interface IItemInsUpdRemCall
	{
		(int? ReturnCode, string Item,
		DateTime? RecordDate) ItemInsUpdRemCallSP(string Site,
		string Item,
		string AbcCode = null,
		int? AcceptReq = 0,
		int? ActiveForCustomerPortal = 0,
		int? ActiveForDataIntegration = 0,
		string AltItem = null,
		string AutoJob = null,
		int? Backflush = 0,
		string BflushLoc = null,
		string Buyer = null,
		string CfgModel = null,
		string Charfld1 = null,
		string Charfld2 = null,
		string Charfld3 = null,
		DateTime? ChgDate = null,
		string CommCode = null,
		string CostMethod = null,
		string CostType = null,
		decimal? CurUCost = null,
		DateTime? Datefld = null,
		int? DaysSupply = null,
		decimal? Decifld1 = null,
		decimal? Decifld2 = null,
		decimal? Decifld3 = null,
		string Description = null,
		int? DockTime = null,
		string DrawingNbr = null,
		int? DuePeriod = null,
		DateTime? EarliestPlannedPoReceipt = null,
		int? ExpLeadTime = null,
		string FamilyCode = null,
		string FeatStr = null,
		string FeatTempl = null,
		int? Featured = 0,
		decimal? FixedOrderQty = null,
		int? InfinitePart = 0,
		decimal? InventoryLclTolerance = null,
		decimal? InventoryUclTolerance = null,
		string IssueBy = "LOT",
		string Job = null,
		int? JobConfigurable = 0,
		int? Kit = 0,
		int? LeadTime = null,
		int? Logifld = null,
		string LotPrefix = null,
		decimal? LotSize = null,
		int? LotTracked = 0,
		int? LowLevel = null,
		string MatlType = null,
		int? MpsFlag = 0,
		int? MpsPlanFence = null,
		int? MrpPart = 0,
		int? OrderConfigurable = 0,
		decimal? OrderMax = null,
		decimal? OrderMin = null,
		decimal? OrderMult = null,
		string Origin = null,
		string Overview = null,
		int? PaperTime = null,
		int? PassReq = 0,
		int? PhantomFlag = 0,
		string PlanCode = null,
		int? PlanFlag = 0,
		string PMTCode = null,
		int? PrintKitComponents = 0,
		string ProdMix = null,
		string ProdType = null,
		string ProductCode = null,
		decimal? QtyAllocjob = null,
		decimal? RatePerDay = null,
		decimal? RcvdOverPoQtyTolerance = null,
		decimal? RcvdUnderPoQtyTolerance = null,
		string ReasonCode = null,
		decimal? ReorderPoint = null,
		int? Reservable = 0,
		string Revision = null,
		decimal? SafetyStockPercent = null,
		int? SerialLength = null,
		string SerialPrefix = null,
		int? SerialTracked = 0,
		string Setupgroup = null,
		int? ShelfLife = null,
		int? ShowInDropDownList = 0,
		decimal? ShrinkFact = null,
		string Stat = null,
		string StatusChgUserCode = null,
		int? Stocked = 0,
		int? Suffix = null,
		string SupplySite = null,
		decimal? SupplyToleranceHrs = null,
		string SupplyWhse = null,
		string TariffClassification = null,
		int? TaxFreeDays = null,
		int? TaxFreeMatl = 0,
		int? TimeFenceRule = 0,
		decimal? TimeFenceValue = null,
		int? TopSeller = 0,
		int? TrackEcn = 0,
		string UM = null,
		decimal? UnitCost = null,
		decimal? UnitWeight = null,
		int? UseReorderPoint = 0,
		decimal? VarExpLead = null,
		decimal? VarLead = null,
		string WeightUnits = null,
		int? SaveCurrentRevUponBomImport = 0,
		int? PreassignLots = 0,
		int? PreassignSerials = 0,
		int? SubjectToExciseTax = 0,
		decimal? ExciseTaxPercent = null,
		int? AllowOnPickList = 0,
		string FlagInsertUpdate = "I",
		DateTime? RecordDate = null,
		string NAFTACountryOfOrigin = null,
        string NAFTAPreferenceCriterion = null,
		decimal? Length = null,
		decimal? Width = null,
		decimal? Height = null,
		string DimensionUM = null,
		string PackageType = null,
		decimal? PackageTypeMaxQty = null,
		int? Hazard = 0,
		string ShippingName = null,
		string UNNum = null,
		string HazardousMatlPackageGroup = null,
		string HazardousMatlClass = null,
		string HazmatContact = null,
		string HazmatContactPhone = null,
		int? HazmatPlacardRequired = 0,
		string NationalMotorFreightClass = null,
		string FreightClass = null);
	}
}

