//PROJECT NAME: Logistics
//CLASS NAME: ISSSFSSROTransValDefItem.cs

using System;
using System.Data;
using CSI.Data.CRUD;
using CSI.Data.SQL.UDDT;

namespace CSI.Logistics.FieldService.Requests
{
	public interface ISSSFSSROTransValDefItem
	{
		(int? ReturnCode, string Whse,
		string Item,
		string ItemDesc,
		string ItemUM,
		int? RtnToStock,
		decimal? UnitCostConv,
		decimal? UnitPriceConv,
		string Lot,
		string Loc,
		decimal? ConvFactor,
		int? SerialTracked,
		int? LotTracked,
		decimal? MatlCostConv,
		decimal? LaborCostConv,
		decimal? FovhdCostConv,
		decimal? VovhdCostConv,
		decimal? OutCostConv,
		decimal? Disc,
		string Prompt,
		string PromptButtons,
		string Infobar,
		string RefType,
		string TaxCode1,
		string TaxCode2,
		int? ItemExists,
		string CustItem,
		string SROCustNum,
		string CostType,
		string LotPrefix,
		string SerialPrefix,
		string TrxRestrictCode,
		string Revision) SSSFSSROTransValDefItemSp(string Table,
		string SRONum,
		int? SROLine,
		int? SROOper,
		DateTime? TransDate,
		string Whse,
		string BillCode,
		string TransType,
		string Item,
		decimal? QtyConv,
		string PriceCurrCode,
		string Pricecode,
		int? ReimbMatl,
		string ItemDesc,
		string ItemUM,
		int? RtnToStock,
		decimal? UnitCostConv,
		decimal? UnitPriceConv,
		string Lot,
		string Loc,
		decimal? ConvFactor,
		int? SerialTracked,
		int? LotTracked,
		decimal? MatlCostConv,
		decimal? LaborCostConv,
		decimal? FovhdCostConv,
		decimal? VovhdCostConv,
		decimal? OutCostConv,
		decimal? Disc,
		string Prompt,
		string PromptButtons,
		string Infobar,
		string RefType = null,
		string Type = "A",
		string TaxCode1 = null,
		string TaxCode2 = null,
		int? ItemExists = null,
		string CustItem = null,
		string SROCustNum = null,
		string CostType = null,
		string LotPrefix = null,
		string SerialPrefix = null,
		int? ValidteItemExistsFlag = 1,
		string TrxRestrictCode = null,
		string Revision = null);
	}
}

