//PROJECT NAME: Logistics
//CLASS NAME: ISSSFSSROTransValidSROMatl.cs

using System;
using System.Data;
using CSI.Data.CRUD;
using CSI.Data.SQL.UDDT;

namespace CSI.Logistics.FieldService.Requests
{
	public interface ISSSFSSROTransValidSROMatl
	{
		(int? ReturnCode, int? SROLine,
		int? SROOper,
		DateTime? TransDate,
		DateTime? PostDate,
		string PartnerID,
		int? PartnerReimbMatl,
		string Dept,
		string Whse,
		string BillCode,
		string TransType,
		int? RtnToStock,
		string Item,
		string ItemDesc,
		string ItemUM,
		string Unit,
		decimal? QtyConv,
		decimal? UnitCostConv,
		decimal? UnitPriceConv,
		string Lot,
		string Loc,
		string TaxCode1,
		string TaxCode2,
		string VatLabel,
		DateTime? ExchDate,
		string UsageType,
		int? SerialTracked,
		int? LotTracked,
		decimal? MatlCostConv,
		decimal? LaborCostConv,
		decimal? FovhdCostConv,
		decimal? VovhdCostConv,
		decimal? OutCostConv,
		decimal? Disc,
		string PriceCode,
		string PriceCurrCode,
		string Prompt,
		string PromptButtons,
		string Infobar,
		string CustItem,
		string SROCustNum,
		string CurAmtFormat,
		string CurCstPrcFormat,
		string ReimbTaxCode1,
		string ReimbTaxCode2,
		string ReimbMethod,
		int? ItemExists,
		string TrxRestrictCode,
		string Revision,
		int? TrackEcn) SSSFSSROTransValidSROMatlSp(string Table,
		string Level,
		string SRONum,
		int? SROLine,
		int? SROOper,
		DateTime? TransDate,
		DateTime? PostDate,
		string PartnerID,
		int? PartnerReimbMatl,
		string Dept,
		string Whse,
		string BillCode,
		string TransType,
		int? RtnToStock,
		string Item,
		string ItemDesc,
		string ItemUM,
		string Unit,
		decimal? QtyConv,
		decimal? UnitCostConv,
		decimal? UnitPriceConv,
		string Lot,
		string Loc,
		string TaxCode1,
		string TaxCode2,
		string VatLabel,
		DateTime? ExchDate,
		string UsageType,
		int? SerialTracked,
		int? LotTracked,
		decimal? MatlCostConv,
		decimal? LaborCostConv,
		decimal? FovhdCostConv,
		decimal? VovhdCostConv,
		decimal? OutCostConv,
		decimal? Disc,
		string PriceCode,
		string PriceCurrCode,
		string Prompt,
		string PromptButtons,
		string Infobar,
		string CustItem,
		string SROCustNum,
		string CurAmtFormat,
		string CurCstPrcFormat,
		string Type = "A",
		string ReimbTaxCode1 = null,
		string ReimbTaxCode2 = null,
		string ReimbMethod = null,
		int? ItemExists = null,
		string TrxRestrictCode = null,
		string Revision = null,
		int? TrackEcn = 0);
	}
}

