namespace CSI.Finance.MTD
{
    public interface IMTDBusinessHandler
    {
        (int returnCode, string message) PerformCodeExchange(
            string doNotTrack,
            string clientConnectMethod,
            string deviceId,
            string localIps,
            string localIpsTimestamp,
            string publicIp,
            string publicIpTimestamp,
            string publicPort,
            string screens,
            string timeZone,
            string windowSize,
            string userAgent,
            string plugins,
            string macAddresses,
            string envOs,
            string code,
            string scope,
            string formName,
            string license,
            string userId,
            string clientVersion);

        (int returnCode, string message) RefreshToken(
            string refreshToken,
            string doNotTrack,
            string clientConnectMethod,
            string deviceId,
            string localIps,
            string localIpsTimestamp,
            string publicIp,
            string publicIpTimestamp,
            string publicPort,
            string screens,
            string timeZone,
            string windowSize,
            string userAgent,
            string plugins,
            string macAddresses,
            string envOs,
            string formName,
            string license,
            string userId,
            string clientVersion);

        (int returnCode, string message) SubmitVat(
            string doNotTrack,
            string clientConnectMethod,
            string deviceId,
            string localIps,
            string localIpsTimestamp,
            string publicIp,
            string publicIpTimestamp,
            string publicPort,
            string screens,
            string timeZone,
            string windowSize,
            string userAgent,
            string plugins,
            string macAddresses,
            string envOs,
            string periodKey,
            string formName,
            string license,
            string userId,
            string clientVersion);

        (int returnCode, string message) RetrieveObligation(
            string doNotTrack,
            string clientConnectMethod,
            string startDate,
            string endDate,
            string deviceId,
            string localIps,
            string localIpsTimestamp,
            string publicIp,
            string publicIpTimestamp,
            string publicPort,
            string screens,
            string timeZone,
            string windowSize,
            string userAgent,
            string plugins,
            string macAddresses,
            string envOs,
            string status,
            string formName,
            string license,
            string userId,
            string clientVersion);

        (int returnCode, string message) GetLiabilities(
            string doNotTrack,
            string clientConnectMethod,
            string startDate,
            string endDate,
            string deviceId,
            string localIps,
            string localIpsTimestamp,
            string publicIp,
            string publicIpTimestamp,
            string publicPort,
            string screens,
            string timeZone,
            string windowSize,
            string userAgent,
            string plugins,
            string macAddresses,
            string envOs,
            string formName,
            string license,
            string periodKey,
            string userId,
            string clientVersion);

        (int returnCode, string message) GetPayments(
            string doNotTrack,
            string clientConnectMethod,
            string startDate,
            string endDate,
            string deviceId,
            string localIps,
            string localIpsTimestamp,
            string publicIp,
            string publicIpTimestamp,
            string publicPort,
            string screens,
            string timeZone,
            string windowSize,
            string userAgent,
            string plugins,
            string macAddresses,
            string envOs,
            string formName,
            string license,
            string periodKey,
            string userId,
            string clientVersion);

        (string localIps, string vrn, string apiUrl, string accessToken, string productName, string vendorVersion, string licenseIds
            , string userIds, bool isWeb, string clientId, string secretKey, string redirectUri, string startDate, string endDate)
            GetBackendParams(
                string doNotTrack,
                string clientConnectMethod,
                string deviceId,
                string localIps,
                string localIpsTimestamp,
                string publicIp,
                string publicIpTimestamp,
                string publicPort,
                string screens,
                string timeZone,
                string windowSize,
                string userAgent,
                string plugins,
                string macAddresses,
                string envOs,
                string formName,
                string license,
                string startDate,
                string endDate,
                string userId,
                bool auth,
                bool isReadAccess,
                string clientVersion);

        (int returnCode, string message) ValidateFraudPreventionHeadersForRetrieveObligation(
            string doNotTrack,
            string clientConnectMethod,
            string startDate,
            string endDate,
            string deviceId,
            string localIps,
            string localIpsTimestamp,
            string publicIp,
            string publicIpTimestamp,
            string publicPort,
            string screens,
            string timeZone,
            string windowSize,
            string userAgent,
            string plugins,
            string macAddresses,
            string envOs,
            string status,
            string formName,
            string license,
            string userId,
            string clientVersion);

        (int returnCode, string message) ValidateFraudPreventionHeadersForGetLiabilities(
            string doNotTrack,
            string clientConnectMethod,
            string startDate,
            string endDate,
            string deviceId,
            string localIps,
            string localIpsTimestamp,
            string publicIp,
            string publicIpTimestamp,
            string publicPort,
            string screens,
            string timeZone,
            string windowSize,
            string userAgent,
            string plugins,
            string macAddresses,
            string envOs,
            string formName,
            string license,
            string periodKey,
            string userId,
            string clientVersion);
    }
}