//PROJECT NAME: Data
//CLASS NAME: IReceiveI.cs

using System;
using System.Data;
using CSI.Data.CRUD;
using CSI.Data.SQL.UDDT;

namespace CSI.Functions
{
	public interface IReceiveI
	{
		(int? ReturnCode,
			string ControlPrefix,
			string ControlSite,
			int? ControlYear,
			int? ControlPeriod,
			decimal? ControlNumber,
			decimal? OldControlNumber,
			string Infobar,
			decimal? TCobyWipMatlC,
			decimal? TCobyWipLbrC,
			decimal? TCobyWipFovhdC,
			decimal? TCobyWipVovhdC,
			decimal? TCobyWipOutC,
			decimal? TCobyWipComp) ReceiveISp(
			string Type,
			string TId,
			decimal? TAdjQty,
			string Whse,
			string Item2,
			string Loc,
			string Lot,
			decimal? TtRate = 1M,
			decimal? DMaterial = 0,
			decimal? DDuty = 0,
			decimal? DFreight = 0,
			decimal? DBrokerage = 0,
			decimal? DInsurance = 0,
			decimal? DLocFrt = 0,
			string VendNum = null,
			string Reference = "",
			string PFromSite = null,
			string PFromCurrCode = null,
			string PToSite = null,
			decimal? PMatlCost = 0,
			decimal? PLbrCost = 0,
			decimal? PFovhdCost = 0,
			decimal? PVovhdCost = 0,
			decimal? POutCost = 0,
			decimal? PTotCost = 0,
			decimal? TMiscCost = 0,
			decimal? TMiscCostM = 0,
			decimal? TMiscCostL = 0,
			decimal? TMiscCostF = 0,
			decimal? TMiscCostV = 0,
			decimal? TMiscCostO = 0,
			decimal? TProfitMarkup = 0,
			string TMiscAcct = null,
			string TMiscAcctUnit1 = null,
			string TMiscAcctUnit2 = null,
			string TMiscAcctUnit3 = null,
			string TMiscAcctUnit4 = null,
			DateTime? TTransDate = null,
			Guid? PMatltranRowPointer = null,
			Guid? PJobRowPointer = null,
			Guid? PJobrouteRowPointer = null,
			Guid? PJobtranRowPointer = null,
			Guid? PPoitemRowPointer = null,
			Guid? PTrnitemRowPointer = null,
			int? Return = 0,
			decimal? TQty = 0,
			decimal? TMaterial = 0,
			decimal? TDuty = 0,
			decimal? TFreight = 0,
			decimal? TBrokerage = 0,
			decimal? TInsurance = 0,
			decimal? TLocFrt = 0,
			string DutyCurrCode = null,
			string FreightCurrCode = null,
			string BrokerageCurrCode = null,
			string InsuranceCurrCode = null,
			string LocFrtCurrCode = null,
			decimal? DutyExchRate = null,
			decimal? FreightExchRate = null,
			decimal? BrokerageExchRate = null,
			decimal? InsuranceExchRate = null,
			decimal? LocFrtExchRate = null,
			string ControlPrefix = null,
			string ControlSite = null,
			int? ControlYear = null,
			int? ControlPeriod = null,
			decimal? ControlNumber = null,
			decimal? OldControlNumber = null,
			string Infobar = null,
			decimal? TCobyWipMatlC = null,
			decimal? TCobyWipLbrC = null,
			decimal? TCobyWipFovhdC = null,
			decimal? TCobyWipVovhdC = null,
			decimal? TCobyWipOutC = null,
			decimal? TCobyWipComp = null,
			int? TCoby = null,
			int? TDoneCoby = null,
			int? TFirstCoby = null,
			string DutyVendNum = null,
			string FreightVendNum = null,
			string BrokerageVendNum = null,
			string InsuranceVendNum = null,
			string LocFrtVendNum = null);
	}
}

