//PROJECT NAME: Logistics
//CLASS NAME: IARPaymentDistPosting.cs

using System;
using System.Data;
using CSI.Data.CRUD;
using CSI.Data.SQL.UDDT;

namespace CSI.Logistics.Customer
{
	public interface IARPaymentDistPosting
	{
		(int? ReturnCode, string Infobar) ARPaymentDistPostingSp(string CorpSite,
		string ReApplyType,
		string ReApplyBankCode,
		decimal? ReApplyDisc,
		decimal? WireExchangeRate,
		DateTime? TIssueDate,
		int? TInvSeq,
		string CorpSiteCurrCode,
		string CorpSiteName,
		Guid? ArpmtRowPointer,
		string ArpmtCustNum,
		string ArpmtBankCode,
		string ArpmtType,
		string ArpmtCreditMemoNum,
		int? ArpmtCheckNum,
		DateTime? ArpmtRecptDate,
		DateTime? ArpmtDueDate,
		string ArpmtRef,
		int? ArpmtNoteExistsFlag,
		string ArpmtDescription,
		int? ArpmtTransferCash,
		string ArpmtdInvNum,
		string ArpmtdSite,
		string ArpmtdApplyCustNum,
		decimal? ArpmtdExchRate,
		decimal? ArpmtdDomDiscAmt,
		decimal? ArpmtdForDiscAmt,
		decimal? ArpmtdDomAllowAmt,
		decimal? ArpmtdForAllowAmt,
		decimal? ArpmtdDomAmtApplied,
		decimal? ArpmtdForAmtApplied,
		string ArpmtdCoNum,
		string ArpmtdDoNum,
		string ArpmtdDiscAcct,
		string ArpmtdDiscAcctUnit1,
		string ArpmtdDiscAcctUnit2,
		string ArpmtdDiscAcctUnit3,
		string ArpmtdDiscAcctUnit4,
		string ArpmtdAllowAcct,
		string ArpmtdAllowAcctUnit1,
		string ArpmtdAllowAcctUnit2,
		string ArpmtdAllowAcctUnit3,
		string ArpmtdAllowAcctUnit4,
		string ArpmtdDepositAcct,
		string ArpmtdDepositAcctUnit1,
		string ArpmtdDepositAcctUnit2,
		string ArpmtdDepositAcctUnit3,
		string ArpmtdDepositAcctUnit4,
		string CorpCustaddrCurrCode,
		int? CorpCustaddrCorpCred,
		string CorpCustaddrCorpCust,
		int? UpdatePrepaidAmt,
		string ControlPrefix,
		string ControlSite,
		int? ControlYear,
		int? ControlPeriod,
		decimal? ControlNumber,
		string Infobar,
		decimal? ArpmtdForTaxAmt1,
		decimal? ArpmtdForTaxAmt2,
		decimal? ArpmtdDomTaxAmt1,
		decimal? ArpmtdDomTaxAmt2,
		int? ArpmtdFsSroDeposit = 0,
		string DepositDebitAcct = null,
		string DepositDebitUnit1 = null,
		string DepositDebitUnit2 = null,
		string DepositDebitUnit3 = null,
		string DepositDebitUnit4 = null,
		decimal? ArpmtdShipmentId = null,
		string TCoNum = null,
		int? TRma = 0,
		DateTime? OrigArpmtRecptDate = null,
		Guid? ArtranHoldNotesRowPointer = null,
        string ArpmtPaymentNumber = null,
        string ArpmtCurrCode = null);
	}
}

