//PROJECT NAME: Data
//CLASS NAME: ICustomerInsUpd.cs

using System;
using System.Data;
using CSI.Data.CRUD;
using CSI.Data.SQL.UDDT;

namespace CSI.Logistics.Customer
{
	public interface ICustomerInsUpd
	{
		int? CustomerInsUpdSp(
			string CustNum,
			int? ApsPullUp = 0,
			decimal? AvgBalOs = null,
			int? AvgDaysOs = null,
			string BankCode = null,
			string BranchId = null,
			DateTime? CalcDate = null,
			string Charfld1 = null,
			string Charfld2 = null,
			string Charfld3 = null,
			decimal? CompanyRevenue = null,
			int? Consolidate = 0,
			string Contact_1 = null,
			string Contact_3 = null,
			string CustBank = null,
			int? CustSeq = null,
			string CustType = null,
			DateTime? Datefld = null,
			string Delterm = null,
			decimal? DiscLstYr = null,
			decimal? DiscYtd = null,
			string DoInvoice = null,
			int? DraftPrintFlag = null,
			int? Einvoice = 0,
			string EndUserType = null,
			int? FinChg = 0,
			int? IncludeTaxInPrice = null,
			string InvCategory = null,
			string InvFreq = null,
			string LangCode = null,
			int? LargDaysOs = null,
			decimal? LargeBalOs = null,
			decimal? LastBalOs = null,
			int? LastDaysOs = null,
			DateTime? LastFinChg = null,
			DateTime? LastInv = null,
			DateTime? LastPaid = null,
			int? LcrReqd = 0,
			int? Logifld = null,
			int? NumberOfEmployees = null,
			int? NumPeriods = null,
			int? OnePackInv = 0,
			int? PayDay = null,
			DateTime? PayDayEndTime_1 = null,
			DateTime? PayDayEndTime_2 = null,
			DateTime? PayDayStartTime_1 = null,
			DateTime? PayDayStartTime_2 = null,
			string PayType = null,
			string Phone_1 = null,
			string Phone_3 = null,
			int? PrintPackInv = 0,
			string ProcessInd = null,
			int? RevisionDay = null,
			DateTime? RevisionDayEndTime_1 = null,
			DateTime? RevisionDayEndTime_2 = null,
			DateTime? RevisionDayStartTime_1 = null,
			DateTime? RevisionDayStartTime_2 = null,
			decimal? SalesLstYr = null,
			decimal? SalesPtd = null,
			decimal? SalesYtd = null,
			string ShipSite = null,
			int? ShowInDropDownList = 0,
			string SICCode = null,
			string StateCycle = null,
			int? Summarize = 0,
			string TermsCode = null,
			string TerritoryCode = null,
			string TransNat = null,
			string TransNat2 = null,
			int? UseExchRate = null,
			int? UseRevisionPayDays = 0,
			string ExportType = null,
			decimal? Decifld1 = null,
			decimal? Decifld2 = null,
			decimal? Decifld3 = null,
			string Pricecode = null,
			int? ActiveForDataIntegration = null,
			string SalesTeamID = null,
			decimal? AmtOverInvAmt = null,
			string BalMethod = null,
			int? CorpAddress = 0,
			int? CorpCred = 0,
			string CorpCust = null,
			int? CreditHold = 0,
			DateTime? CreditHoldDate = null,
			string CreditHoldReason = null,
			string CreditHoldUser = null,
			decimal? CreditLimit = null,
			decimal? OrderCreditLimit = null,
			string CurrCode = null,
			int? DaysOverInvDueDate = null,
			string ExternalEmailAddr = null,
			string FaxNum = null,
			string InternalEmailAddr = null,
			string InternetUrl = null,
			string TelexNum = null,
			string Addr_1 = null,
			string Addr_2 = null,
			string Addr_3 = null,
			string Addr_4 = null,
			string City = null,
			string Country = null,
			string County = null,
			string Name = null,
			string State = null,
			string Zip = null,
			int? DefaultShipTo = null,
			int? DaysShippedBeforeDueDate = null,
			int? DaysShippedAfterDueDate = null,
			decimal? ShippedOverOrderedQty = null,
			decimal? ShippedUnderOrderedQty = null,
			string FlagInsertUpdate = "I",
			string ResellerSlsman = null,
			int? ShipmentApprovalRequired = null,
			decimal? ConstructiveSalePricePct = null,
			string SepaMandateRef = null,
			DateTime? SepaMandateCreationDate = null,
			DateTime? SepaMandateExpirationDate = null,
			DateTime? SepaMndateLastUsedDate = null,
			int? SepaCoreDirectDebit = null,
			int? SepaOneOffMandate = null,
			string BankAcctNo = null,
			string AccountName = null,
			string InternationalBankAccount = null,
			string BankAuthorityPartyId = null,
			string DunningGroup = null,
			int? DunningStageId = null,
			DateTime? LastDunningDate = null,
			Guid? RowPointer = null,
			int? OneShipmentInv = 0,
			string ShipMethodGroup = null,
			string Stat = null,
			int? UseLongName = 0,
			string LongName = null);
	}
}

