//PROJECT NAME: Logistics
//CLASS NAME: ICustOrderLinesFormDefaults.cs

using System;
using System.Data;
using CSI.Data.CRUD;
using CSI.Data.SQL.UDDT;

namespace CSI.Logistics.Customer
{
	public interface ICustOrderLinesFormDefaults
	{
		(int? ReturnCode, string ShipSite,
		string Stat,
		string Item,
		string UM,
		decimal? QtyOrderedConv,
		DateTime? DueDate,
		decimal? Price,
		decimal? PriceConv,
		string CustItem,
		string TransNat,
		string TrnDesc,
		string TransNat2,
		string Trn2Desc,
		string Delterm,
		string DeltermDesc,
		string ProcessInd,
		string EcCode,
		string Origin,
		string CommCode,
		decimal? SupplQty,
		decimal? ExportValue,
		string CustNum,
		int? CustSeq,
		string Whse,
		string Pricecode,
		string CoOrigSite,
		int? Reprice,
		int? Consolidate,
		int? Summarize,
		string InvFreq,
		string RefType,
		string Transport,
		string TaxCode1,
		string TaxCode1Desc,
		string TaxCode2,
		string TaxCode2Desc,
		string CurrCode,
		string CurrAmtFormat,
		string CurrCstPrcFormat,
		int? SupplQtyReq,
		decimal? SupplQtyConvFactor,
		string CoStat,
		string Infobar,
		DateTime? ExpDate,
		string EUCode,
		string TaxCode1Type,
		string TaxRegNum1) CustOrderLinesFormDefaultsSp(string CoNum,
		string ShipSite,
		string Stat,
		string Item,
		string UM,
		decimal? QtyOrderedConv,
		DateTime? DueDate,
		decimal? Price,
		decimal? PriceConv,
		string CustItem,
		string TransNat,
		string TrnDesc,
		string TransNat2,
		string Trn2Desc,
		string Delterm,
		string DeltermDesc,
		string ProcessInd,
		string EcCode,
		string Origin,
		string CommCode,
		decimal? SupplQty,
		decimal? ExportValue,
		string CustNum,
		int? CustSeq,
		string Whse,
		string Pricecode,
		string CoOrigSite,
		int? Reprice,
		int? Consolidate,
		int? Summarize,
		string InvFreq,
		string RefType,
		string Transport,
		string TaxCode1,
		string TaxCode1Desc,
		string TaxCode2,
		string TaxCode2Desc,
		string CurrCode,
		string CurrAmtFormat,
		string CurrCstPrcFormat,
		int? SupplQtyReq,
		decimal? SupplQtyConvFactor,
		string CoStat,
		string Infobar,
		DateTime? ExpDate = null,
		string EUCode = null,
		string TaxCode1Type = null,
		string TaxRegNum1 = null);
	}
}

