//PROJECT NAME: MG.MGCore
//CLASS NAME: RemoteMethodCall.cs

using CSI.Data.SQL.UDDT;
using System;
using System.Data;
using CSI.Data.CRUD;
using CSI.Data.RecordSets;
using CSI.MG;

namespace CSI.MG.MGCore
{
    public class RemoteMethodCall : IRemoteMethodCall
    {
        IApplicationDB appDB;
        IBunchedLoadCollection bunchedLoadCollection;
        IDataTableToCollectionLoadResponse dataTableToCollectionLoadResponse;

        public RemoteMethodCall(IApplicationDB appDB, IBunchedLoadCollection bunchedLoadCollection, IDataTableToCollectionLoadResponse dataTableToCollectionLoadResponse)
        {
            this.appDB = appDB;
            this.bunchedLoadCollection = bunchedLoadCollection;
            this.dataTableToCollectionLoadResponse = dataTableToCollectionLoadResponse;
        }

        public (ICollectionLoadResponse Data, int? ReturnCode, string Infobar) RemoteMethodCallSp(string Site,
        string IdoName,
        string MethodName,
        string StoredProcName = null,
        string Infobar = null,
        string Parm1Value = "",
        string Parm2Value = "",
        string Parm3Value = "",
        string Parm4Value = "",
        string Parm5Value = "",
        string Parm6Value = "",
        string Parm7Value = "",
        string Parm8Value = "",
        string Parm9Value = "",
        string Parm10Value = "",
        string Parm11Value = "",
        string Parm12Value = "",
        string Parm13Value = "",
        string Parm14Value = "",
        string Parm15Value = "",
        string Parm16Value = "",
        string Parm17Value = "",
        string Parm18Value = "",
        string Parm19Value = "",
        string Parm20Value = "",
        string Parm21Value = "",
        string Parm22Value = "",
        string Parm23Value = "",
        string Parm24Value = "",
        string Parm25Value = "",
        string Parm26Value = "",
        string Parm27Value = "",
        string Parm28Value = "",
        string Parm29Value = "",
        string Parm30Value = "",
        string Parm31Value = "",
        string Parm32Value = "",
        string Parm33Value = "",
        string Parm34Value = "",
        string Parm35Value = "",
        string Parm36Value = "",
        string Parm37Value = "",
        string Parm38Value = "",
        string Parm39Value = "",
        string Parm40Value = "",
        string Parm41Value = "",
        string Parm42Value = "",
        string Parm43Value = "",
        string Parm44Value = "",
        string Parm45Value = "",
        string Parm46Value = "",
        string Parm47Value = "",
        string Parm48Value = "",
        string Parm49Value = "",
        string Parm50Value = "",
        string Parm51Value = "",
        string Parm52Value = "",
        string Parm53Value = "",
        string Parm54Value = "",
        string Parm55Value = "",
        string Parm56Value = "",
        string Parm57Value = "",
        string Parm58Value = "",
        string Parm59Value = "",
        string Parm60Value = "",
        string Parm61Value = "",
        string Parm62Value = "",
        string Parm63Value = "",
        string Parm64Value = "",
        string Parm65Value = "",
        string Parm66Value = "",
        string Parm67Value = "",
        string Parm68Value = "",
        string Parm69Value = "",
        string Parm70Value = "",
        string Parm71Value = "",
        string Parm72Value = "",
        string Parm73Value = "",
        string Parm74Value = "",
        string Parm75Value = "",
        string Parm76Value = "",
        string Parm77Value = "",
        string Parm78Value = "",
        string Parm79Value = "",
        string Parm80Value = "",
        string Parm81Value = "",
        string Parm82Value = "",
        string Parm83Value = "",
        string Parm84Value = "",
        string Parm85Value = "",
        string Parm86Value = "",
        string Parm87Value = "",
        string Parm88Value = "",
        string Parm89Value = "",
        string Parm90Value = "",
        string Parm91Value = "",
        string Parm92Value = "",
        string Parm93Value = "",
        string Parm94Value = "",
        string Parm95Value = "",
        string Parm96Value = "",
        string Parm97Value = "",
        string Parm98Value = "",
        string Parm99Value = "",
        string Parm100Value = "",
        string Parm101Value = "",
        string Parm102Value = "",
        string Parm103Value = "",
        string Parm104Value = "",
        string Parm105Value = "",
        string Parm106Value = "",
        string Parm107Value = "",
        string Parm108Value = "",
        string Parm109Value = "",
        string Parm110Value = "",
        string Parm111Value = "",
        string Parm112Value = "",
        string Parm113Value = "",
        string Parm114Value = "",
        string Parm115Value = "",
        string Parm116Value = "",
        string Parm117Value = "",
        string Parm118Value = "",
        string Parm119Value = "",
        string Parm120Value = "",
        string Parm121Value = "",
        string Parm122Value = "",
        string Parm123Value = "",
        string Parm124Value = "",
        string Parm125Value = "",
        string Parm126Value = "",
        string Parm127Value = "",
        string Parm128Value = "",
        string Parm129Value = "",
        string Parm130Value = "",
        string Parm131Value = "",
        string Parm132Value = "",
        string Parm133Value = "",
        string Parm134Value = "",
        string Parm135Value = "",
        string Parm136Value = "",
        string Parm137Value = "",
        string Parm138Value = "",
        string Parm139Value = "",
        string Parm140Value = "",
        string Parm141Value = "",
        string Parm142Value = "",
        string Parm143Value = "",
        string Parm144Value = "",
        string Parm145Value = "",
        string Parm146Value = "",
        string Parm147Value = "",
        string Parm148Value = "",
        string Parm149Value = "",
        string Parm150Value = "",
        string Parm151Value = "",
        string Parm152Value = "",
        string Parm153Value = "",
        string Parm154Value = "",
        string Parm155Value = "",
        string Parm156Value = "",
        string Parm157Value = "",
        string Parm158Value = "",
        string Parm159Value = "",
        string Parm160Value = "",
        string Parm161Value = "",
        string Parm162Value = "",
        string Parm163Value = "",
        string Parm164Value = "",
        string Parm165Value = "",
        string Parm166Value = "",
        string Parm167Value = "",
        string Parm168Value = "",
        string Parm169Value = "",
        string Parm170Value = "",
        string Parm171Value = "",
        string Parm172Value = "",
        string Parm173Value = "",
        string Parm174Value = "",
        string Parm175Value = "",
        string Parm176Value = "",
        string Parm177Value = "",
        string Parm178Value = "",
        string Parm179Value = "",
        string Parm180Value = "",
        string Parm181Value = "",
        string Parm182Value = "",
        string Parm183Value = "",
        string Parm184Value = "",
        string Parm185Value = "",
        string Parm186Value = "",
        string Parm187Value = "",
        string Parm188Value = "",
        string Parm189Value = "",
        string Parm190Value = "",
        string Parm191Value = "",
        string Parm192Value = "",
        string Parm193Value = "",
        string Parm194Value = "",
        string Parm195Value = "",
        string Parm196Value = "",
        string Parm197Value = "",
        string Parm198Value = "",
        string Parm199Value = "",
        string Parm200Value = "",
        Guid RefRowPointer = default(Guid))
        {
            SiteType _Site = Site;
            StringType _IdoName = IdoName;
            StringType _MethodName = MethodName;
            StringType _StoredProcName = StoredProcName;
            InfobarType _Infobar = Infobar;
            VeryLongListType _Parm1Value = Parm1Value;
            VeryLongListType _Parm2Value = Parm2Value;
            VeryLongListType _Parm3Value = Parm3Value;
            VeryLongListType _Parm4Value = Parm4Value;
            VeryLongListType _Parm5Value = Parm5Value;
            VeryLongListType _Parm6Value = Parm6Value;
            VeryLongListType _Parm7Value = Parm7Value;
            VeryLongListType _Parm8Value = Parm8Value;
            VeryLongListType _Parm9Value = Parm9Value;
            VeryLongListType _Parm10Value = Parm10Value;
            VeryLongListType _Parm11Value = Parm11Value;
            VeryLongListType _Parm12Value = Parm12Value;
            VeryLongListType _Parm13Value = Parm13Value;
            VeryLongListType _Parm14Value = Parm14Value;
            VeryLongListType _Parm15Value = Parm15Value;
            VeryLongListType _Parm16Value = Parm16Value;
            VeryLongListType _Parm17Value = Parm17Value;
            VeryLongListType _Parm18Value = Parm18Value;
            VeryLongListType _Parm19Value = Parm19Value;
            VeryLongListType _Parm20Value = Parm20Value;
            VeryLongListType _Parm21Value = Parm21Value;
            VeryLongListType _Parm22Value = Parm22Value;
            VeryLongListType _Parm23Value = Parm23Value;
            VeryLongListType _Parm24Value = Parm24Value;
            VeryLongListType _Parm25Value = Parm25Value;
            VeryLongListType _Parm26Value = Parm26Value;
            VeryLongListType _Parm27Value = Parm27Value;
            VeryLongListType _Parm28Value = Parm28Value;
            VeryLongListType _Parm29Value = Parm29Value;
            VeryLongListType _Parm30Value = Parm30Value;
            VeryLongListType _Parm31Value = Parm31Value;
            VeryLongListType _Parm32Value = Parm32Value;
            VeryLongListType _Parm33Value = Parm33Value;
            VeryLongListType _Parm34Value = Parm34Value;
            VeryLongListType _Parm35Value = Parm35Value;
            VeryLongListType _Parm36Value = Parm36Value;
            VeryLongListType _Parm37Value = Parm37Value;
            VeryLongListType _Parm38Value = Parm38Value;
            VeryLongListType _Parm39Value = Parm39Value;
            VeryLongListType _Parm40Value = Parm40Value;
            VeryLongListType _Parm41Value = Parm41Value;
            VeryLongListType _Parm42Value = Parm42Value;
            VeryLongListType _Parm43Value = Parm43Value;
            VeryLongListType _Parm44Value = Parm44Value;
            VeryLongListType _Parm45Value = Parm45Value;
            VeryLongListType _Parm46Value = Parm46Value;
            VeryLongListType _Parm47Value = Parm47Value;
            VeryLongListType _Parm48Value = Parm48Value;
            VeryLongListType _Parm49Value = Parm49Value;
            VeryLongListType _Parm50Value = Parm50Value;
            VeryLongListType _Parm51Value = Parm51Value;
            VeryLongListType _Parm52Value = Parm52Value;
            VeryLongListType _Parm53Value = Parm53Value;
            VeryLongListType _Parm54Value = Parm54Value;
            VeryLongListType _Parm55Value = Parm55Value;
            VeryLongListType _Parm56Value = Parm56Value;
            VeryLongListType _Parm57Value = Parm57Value;
            VeryLongListType _Parm58Value = Parm58Value;
            VeryLongListType _Parm59Value = Parm59Value;
            VeryLongListType _Parm60Value = Parm60Value;
            VeryLongListType _Parm61Value = Parm61Value;
            VeryLongListType _Parm62Value = Parm62Value;
            VeryLongListType _Parm63Value = Parm63Value;
            VeryLongListType _Parm64Value = Parm64Value;
            VeryLongListType _Parm65Value = Parm65Value;
            VeryLongListType _Parm66Value = Parm66Value;
            VeryLongListType _Parm67Value = Parm67Value;
            VeryLongListType _Parm68Value = Parm68Value;
            VeryLongListType _Parm69Value = Parm69Value;
            VeryLongListType _Parm70Value = Parm70Value;
            VeryLongListType _Parm71Value = Parm71Value;
            VeryLongListType _Parm72Value = Parm72Value;
            VeryLongListType _Parm73Value = Parm73Value;
            VeryLongListType _Parm74Value = Parm74Value;
            VeryLongListType _Parm75Value = Parm75Value;
            VeryLongListType _Parm76Value = Parm76Value;
            VeryLongListType _Parm77Value = Parm77Value;
            VeryLongListType _Parm78Value = Parm78Value;
            VeryLongListType _Parm79Value = Parm79Value;
            VeryLongListType _Parm80Value = Parm80Value;
            VeryLongListType _Parm81Value = Parm81Value;
            VeryLongListType _Parm82Value = Parm82Value;
            VeryLongListType _Parm83Value = Parm83Value;
            VeryLongListType _Parm84Value = Parm84Value;
            VeryLongListType _Parm85Value = Parm85Value;
            VeryLongListType _Parm86Value = Parm86Value;
            VeryLongListType _Parm87Value = Parm87Value;
            VeryLongListType _Parm88Value = Parm88Value;
            VeryLongListType _Parm89Value = Parm89Value;
            VeryLongListType _Parm90Value = Parm90Value;
            VeryLongListType _Parm91Value = Parm91Value;
            VeryLongListType _Parm92Value = Parm92Value;
            VeryLongListType _Parm93Value = Parm93Value;
            VeryLongListType _Parm94Value = Parm94Value;
            VeryLongListType _Parm95Value = Parm95Value;
            VeryLongListType _Parm96Value = Parm96Value;
            VeryLongListType _Parm97Value = Parm97Value;
            VeryLongListType _Parm98Value = Parm98Value;
            VeryLongListType _Parm99Value = Parm99Value;
            VeryLongListType _Parm100Value = Parm100Value;
            VeryLongListType _Parm101Value = Parm101Value;
            VeryLongListType _Parm102Value = Parm102Value;
            VeryLongListType _Parm103Value = Parm103Value;
            VeryLongListType _Parm104Value = Parm104Value;
            VeryLongListType _Parm105Value = Parm105Value;
            VeryLongListType _Parm106Value = Parm106Value;
            VeryLongListType _Parm107Value = Parm107Value;
            VeryLongListType _Parm108Value = Parm108Value;
            VeryLongListType _Parm109Value = Parm109Value;
            VeryLongListType _Parm110Value = Parm110Value;
            VeryLongListType _Parm111Value = Parm111Value;
            VeryLongListType _Parm112Value = Parm112Value;
            VeryLongListType _Parm113Value = Parm113Value;
            VeryLongListType _Parm114Value = Parm114Value;
            VeryLongListType _Parm115Value = Parm115Value;
            VeryLongListType _Parm116Value = Parm116Value;
            VeryLongListType _Parm117Value = Parm117Value;
            VeryLongListType _Parm118Value = Parm118Value;
            VeryLongListType _Parm119Value = Parm119Value;
            VeryLongListType _Parm120Value = Parm120Value;
            VeryLongListType _Parm121Value = Parm121Value;
            VeryLongListType _Parm122Value = Parm122Value;
            VeryLongListType _Parm123Value = Parm123Value;
            VeryLongListType _Parm124Value = Parm124Value;
            VeryLongListType _Parm125Value = Parm125Value;
            VeryLongListType _Parm126Value = Parm126Value;
            VeryLongListType _Parm127Value = Parm127Value;
            VeryLongListType _Parm128Value = Parm128Value;
            VeryLongListType _Parm129Value = Parm129Value;
            VeryLongListType _Parm130Value = Parm130Value;
            VeryLongListType _Parm131Value = Parm131Value;
            VeryLongListType _Parm132Value = Parm132Value;
            VeryLongListType _Parm133Value = Parm133Value;
            VeryLongListType _Parm134Value = Parm134Value;
            VeryLongListType _Parm135Value = Parm135Value;
            VeryLongListType _Parm136Value = Parm136Value;
            VeryLongListType _Parm137Value = Parm137Value;
            VeryLongListType _Parm138Value = Parm138Value;
            VeryLongListType _Parm139Value = Parm139Value;
            VeryLongListType _Parm140Value = Parm140Value;
            VeryLongListType _Parm141Value = Parm141Value;
            VeryLongListType _Parm142Value = Parm142Value;
            VeryLongListType _Parm143Value = Parm143Value;
            VeryLongListType _Parm144Value = Parm144Value;
            VeryLongListType _Parm145Value = Parm145Value;
            VeryLongListType _Parm146Value = Parm146Value;
            VeryLongListType _Parm147Value = Parm147Value;
            VeryLongListType _Parm148Value = Parm148Value;
            VeryLongListType _Parm149Value = Parm149Value;
            VeryLongListType _Parm150Value = Parm150Value;
            VeryLongListType _Parm151Value = Parm151Value;
            VeryLongListType _Parm152Value = Parm152Value;
            VeryLongListType _Parm153Value = Parm153Value;
            VeryLongListType _Parm154Value = Parm154Value;
            VeryLongListType _Parm155Value = Parm155Value;
            VeryLongListType _Parm156Value = Parm156Value;
            VeryLongListType _Parm157Value = Parm157Value;
            VeryLongListType _Parm158Value = Parm158Value;
            VeryLongListType _Parm159Value = Parm159Value;
            VeryLongListType _Parm160Value = Parm160Value;
            VeryLongListType _Parm161Value = Parm161Value;
            VeryLongListType _Parm162Value = Parm162Value;
            VeryLongListType _Parm163Value = Parm163Value;
            VeryLongListType _Parm164Value = Parm164Value;
            VeryLongListType _Parm165Value = Parm165Value;
            VeryLongListType _Parm166Value = Parm166Value;
            VeryLongListType _Parm167Value = Parm167Value;
            VeryLongListType _Parm168Value = Parm168Value;
            VeryLongListType _Parm169Value = Parm169Value;
            VeryLongListType _Parm170Value = Parm170Value;
            VeryLongListType _Parm171Value = Parm171Value;
            VeryLongListType _Parm172Value = Parm172Value;
            VeryLongListType _Parm173Value = Parm173Value;
            VeryLongListType _Parm174Value = Parm174Value;
            VeryLongListType _Parm175Value = Parm175Value;
            VeryLongListType _Parm176Value = Parm176Value;
            VeryLongListType _Parm177Value = Parm177Value;
            VeryLongListType _Parm178Value = Parm178Value;
            VeryLongListType _Parm179Value = Parm179Value;
            VeryLongListType _Parm180Value = Parm180Value;
            VeryLongListType _Parm181Value = Parm181Value;
            VeryLongListType _Parm182Value = Parm182Value;
            VeryLongListType _Parm183Value = Parm183Value;
            VeryLongListType _Parm184Value = Parm184Value;
            VeryLongListType _Parm185Value = Parm185Value;
            VeryLongListType _Parm186Value = Parm186Value;
            VeryLongListType _Parm187Value = Parm187Value;
            VeryLongListType _Parm188Value = Parm188Value;
            VeryLongListType _Parm189Value = Parm189Value;
            VeryLongListType _Parm190Value = Parm190Value;
            VeryLongListType _Parm191Value = Parm191Value;
            VeryLongListType _Parm192Value = Parm192Value;
            VeryLongListType _Parm193Value = Parm193Value;
            VeryLongListType _Parm194Value = Parm194Value;
            VeryLongListType _Parm195Value = Parm195Value;
            VeryLongListType _Parm196Value = Parm196Value;
            VeryLongListType _Parm197Value = Parm197Value;
            VeryLongListType _Parm198Value = Parm198Value;
            VeryLongListType _Parm199Value = Parm199Value;
            VeryLongListType _Parm200Value = Parm200Value;
            RowPointerType _RefRowPointer = RefRowPointer;

            using (IDbCommand cmd = appDB.CreateCommand())
            {
                DataTable dtReturn = new DataTable();

                cmd.CommandType = CommandType.StoredProcedure;
                cmd.CommandText = "RemoteMethodCallSp";

                appDB.AddCommandParameter(cmd, "Site", _Site, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "IdoName", _IdoName, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "MethodName", _MethodName, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "StoredProcName", _StoredProcName, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Infobar", _Infobar, ParameterDirection.InputOutput);
                appDB.AddCommandParameter(cmd, "Parm1Value", _Parm1Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm2Value", _Parm2Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm3Value", _Parm3Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm4Value", _Parm4Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm5Value", _Parm5Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm6Value", _Parm6Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm7Value", _Parm7Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm8Value", _Parm8Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm9Value", _Parm9Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm10Value", _Parm10Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm11Value", _Parm11Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm12Value", _Parm12Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm13Value", _Parm13Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm14Value", _Parm14Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm15Value", _Parm15Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm16Value", _Parm16Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm17Value", _Parm17Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm18Value", _Parm18Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm19Value", _Parm19Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm20Value", _Parm20Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm21Value", _Parm21Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm22Value", _Parm22Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm23Value", _Parm23Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm24Value", _Parm24Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm25Value", _Parm25Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm26Value", _Parm26Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm27Value", _Parm27Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm28Value", _Parm28Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm29Value", _Parm29Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm30Value", _Parm30Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm31Value", _Parm31Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm32Value", _Parm32Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm33Value", _Parm33Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm34Value", _Parm34Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm35Value", _Parm35Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm36Value", _Parm36Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm37Value", _Parm37Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm38Value", _Parm38Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm39Value", _Parm39Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm40Value", _Parm40Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm41Value", _Parm41Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm42Value", _Parm42Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm43Value", _Parm43Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm44Value", _Parm44Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm45Value", _Parm45Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm46Value", _Parm46Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm47Value", _Parm47Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm48Value", _Parm48Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm49Value", _Parm49Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm50Value", _Parm50Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm51Value", _Parm51Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm52Value", _Parm52Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm53Value", _Parm53Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm54Value", _Parm54Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm55Value", _Parm55Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm56Value", _Parm56Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm57Value", _Parm57Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm58Value", _Parm58Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm59Value", _Parm59Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm60Value", _Parm60Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm61Value", _Parm61Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm62Value", _Parm62Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm63Value", _Parm63Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm64Value", _Parm64Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm65Value", _Parm65Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm66Value", _Parm66Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm67Value", _Parm67Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm68Value", _Parm68Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm69Value", _Parm69Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm70Value", _Parm70Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm71Value", _Parm71Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm72Value", _Parm72Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm73Value", _Parm73Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm74Value", _Parm74Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm75Value", _Parm75Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm76Value", _Parm76Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm77Value", _Parm77Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm78Value", _Parm78Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm79Value", _Parm79Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm80Value", _Parm80Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm81Value", _Parm81Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm82Value", _Parm82Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm83Value", _Parm83Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm84Value", _Parm84Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm85Value", _Parm85Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm86Value", _Parm86Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm87Value", _Parm87Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm88Value", _Parm88Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm89Value", _Parm89Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm90Value", _Parm90Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm91Value", _Parm91Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm92Value", _Parm92Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm93Value", _Parm93Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm94Value", _Parm94Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm95Value", _Parm95Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm96Value", _Parm96Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm97Value", _Parm97Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm98Value", _Parm98Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm99Value", _Parm99Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm100Value", _Parm100Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm101Value", _Parm101Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm102Value", _Parm102Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm103Value", _Parm103Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm104Value", _Parm104Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm105Value", _Parm105Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm106Value", _Parm106Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm107Value", _Parm107Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm108Value", _Parm108Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm109Value", _Parm109Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm110Value", _Parm110Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm111Value", _Parm111Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm112Value", _Parm112Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm113Value", _Parm113Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm114Value", _Parm114Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm115Value", _Parm115Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm116Value", _Parm116Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm117Value", _Parm117Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm118Value", _Parm118Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm119Value", _Parm119Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm120Value", _Parm120Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm121Value", _Parm121Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm122Value", _Parm122Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm123Value", _Parm123Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm124Value", _Parm124Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm125Value", _Parm125Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm126Value", _Parm126Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm127Value", _Parm127Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm128Value", _Parm128Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm129Value", _Parm129Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm130Value", _Parm130Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm131Value", _Parm131Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm132Value", _Parm132Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm133Value", _Parm133Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm134Value", _Parm134Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm135Value", _Parm135Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm136Value", _Parm136Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm137Value", _Parm137Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm138Value", _Parm138Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm139Value", _Parm139Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm140Value", _Parm140Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm141Value", _Parm141Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm142Value", _Parm142Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm143Value", _Parm143Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm144Value", _Parm144Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm145Value", _Parm145Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm146Value", _Parm146Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm147Value", _Parm147Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm148Value", _Parm148Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm149Value", _Parm149Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm150Value", _Parm150Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm151Value", _Parm151Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm152Value", _Parm152Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm153Value", _Parm153Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm154Value", _Parm154Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm155Value", _Parm155Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm156Value", _Parm156Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm157Value", _Parm157Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm158Value", _Parm158Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm159Value", _Parm159Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm160Value", _Parm160Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm161Value", _Parm161Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm162Value", _Parm162Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm163Value", _Parm163Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm164Value", _Parm164Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm165Value", _Parm165Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm166Value", _Parm166Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm167Value", _Parm167Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm168Value", _Parm168Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm169Value", _Parm169Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm170Value", _Parm170Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm171Value", _Parm171Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm172Value", _Parm172Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm173Value", _Parm173Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm174Value", _Parm174Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm175Value", _Parm175Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm176Value", _Parm176Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm177Value", _Parm177Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm178Value", _Parm178Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm179Value", _Parm179Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm180Value", _Parm180Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm181Value", _Parm181Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm182Value", _Parm182Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm183Value", _Parm183Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm184Value", _Parm184Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm185Value", _Parm185Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm186Value", _Parm186Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm187Value", _Parm187Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm188Value", _Parm188Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm189Value", _Parm189Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm190Value", _Parm190Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm191Value", _Parm191Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm192Value", _Parm192Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm193Value", _Parm193Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm194Value", _Parm194Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm195Value", _Parm195Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm196Value", _Parm196Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm197Value", _Parm197Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm198Value", _Parm198Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm199Value", _Parm199Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "Parm200Value", _Parm200Value, ParameterDirection.Input);
                appDB.AddCommandParameter(cmd, "RefRowPointer", _RefRowPointer, ParameterDirection.Input);

                IntType returnVal = 0;
                IDbDataParameter dbParm = appDB.AddCommandParameter(cmd, "ReturnVal", returnVal, ParameterDirection.ReturnValue);
                dbParm.DbType = DbType.Int32;

                dtReturn = appDB.ExecuteQuery(cmd);

                Infobar = _Infobar;

                return (dataTableToCollectionLoadResponse.Process(dtReturn), (int)((IDbDataParameter)cmd.Parameters["@ReturnVal"]).Value, Infobar);
            }
        }
    }
}
